#ifndef GLOBAL_HEADER_H
#define GLOBAL_HEADER_H

#define SHAREDLIB_LIBRARY

#if defined(SHAREDLIB_LIBRARY)
#  define SHAREDLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHAREDLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GLOBAL_HEADER_H
