/* soapH.h
   Generated by gSOAP 2.8.7 from vatCheckService.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef soap_write_bool
#define soap_write_bool(soap, data) ( soap_begin_send(soap) || soap_put_bool(soap, data, "boolean", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);

#ifndef soap_read_bool
#define soap_read_bool(soap, data) ( soap_begin_recv(soap) || !soap_get_bool(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__matchCode
#define SOAP_TYPE_ns2__matchCode (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__matchCode(struct soap*, enum ns2__matchCode *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__matchCode(struct soap*, const char*, int, const enum ns2__matchCode *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns2__matchCode2s(struct soap*, enum ns2__matchCode);
SOAP_FMAC3 enum ns2__matchCode * SOAP_FMAC4 soap_in_ns2__matchCode(struct soap*, const char*, enum ns2__matchCode *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns2__matchCode(struct soap*, const char*, enum ns2__matchCode *);

#ifndef soap_write_ns2__matchCode
#define soap_write_ns2__matchCode(soap, data) ( soap_begin_send(soap) || soap_put_ns2__matchCode(soap, data, "ns2:matchCode", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__matchCode(struct soap*, const enum ns2__matchCode *, const char*, const char*);

#ifndef soap_read_ns2__matchCode
#define soap_read_ns2__matchCode(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__matchCode(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum ns2__matchCode * SOAP_FMAC4 soap_get_ns2__matchCode(struct soap*, enum ns2__matchCode *, const char*, const char*);

#ifndef SOAP_TYPE__ns2__checkVatApproxResponse
#define SOAP_TYPE__ns2__checkVatApproxResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__checkVatApproxResponse(struct soap*, const char*, int, const _ns2__checkVatApproxResponse *, const char*);
SOAP_FMAC3 _ns2__checkVatApproxResponse * SOAP_FMAC4 soap_in__ns2__checkVatApproxResponse(struct soap*, const char*, _ns2__checkVatApproxResponse *, const char*);

#ifndef soap_write__ns2__checkVatApproxResponse
#define soap_write__ns2__checkVatApproxResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:checkVatApproxResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__checkVatApproxResponse
#define soap_read__ns2__checkVatApproxResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__checkVatApproxResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__checkVatApproxResponse * SOAP_FMAC4 soap_get__ns2__checkVatApproxResponse(struct soap*, _ns2__checkVatApproxResponse *, const char*, const char*);

#define soap_new__ns2__checkVatApproxResponse(soap, n) soap_instantiate__ns2__checkVatApproxResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__checkVatApproxResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__checkVatApproxResponse * SOAP_FMAC2 soap_instantiate__ns2__checkVatApproxResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__checkVatApproxResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__checkVatApprox
#define SOAP_TYPE__ns2__checkVatApprox (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__checkVatApprox(struct soap*, const char*, int, const _ns2__checkVatApprox *, const char*);
SOAP_FMAC3 _ns2__checkVatApprox * SOAP_FMAC4 soap_in__ns2__checkVatApprox(struct soap*, const char*, _ns2__checkVatApprox *, const char*);

#ifndef soap_write__ns2__checkVatApprox
#define soap_write__ns2__checkVatApprox(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:checkVatApprox", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__checkVatApprox
#define soap_read__ns2__checkVatApprox(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__checkVatApprox(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__checkVatApprox * SOAP_FMAC4 soap_get__ns2__checkVatApprox(struct soap*, _ns2__checkVatApprox *, const char*, const char*);

#define soap_new__ns2__checkVatApprox(soap, n) soap_instantiate__ns2__checkVatApprox(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__checkVatApprox(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__checkVatApprox * SOAP_FMAC2 soap_instantiate__ns2__checkVatApprox(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__checkVatApprox(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__checkVatResponse
#define SOAP_TYPE__ns2__checkVatResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__checkVatResponse(struct soap*, const char*, int, const _ns2__checkVatResponse *, const char*);
SOAP_FMAC3 _ns2__checkVatResponse * SOAP_FMAC4 soap_in__ns2__checkVatResponse(struct soap*, const char*, _ns2__checkVatResponse *, const char*);

#ifndef soap_write__ns2__checkVatResponse
#define soap_write__ns2__checkVatResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:checkVatResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__checkVatResponse
#define soap_read__ns2__checkVatResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__checkVatResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__checkVatResponse * SOAP_FMAC4 soap_get__ns2__checkVatResponse(struct soap*, _ns2__checkVatResponse *, const char*, const char*);

#define soap_new__ns2__checkVatResponse(soap, n) soap_instantiate__ns2__checkVatResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__checkVatResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__checkVatResponse * SOAP_FMAC2 soap_instantiate__ns2__checkVatResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__checkVatResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__checkVat
#define SOAP_TYPE__ns2__checkVat (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__checkVat(struct soap*, const char*, int, const _ns2__checkVat *, const char*);
SOAP_FMAC3 _ns2__checkVat * SOAP_FMAC4 soap_in__ns2__checkVat(struct soap*, const char*, _ns2__checkVat *, const char*);

#ifndef soap_write__ns2__checkVat
#define soap_write__ns2__checkVat(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:checkVat", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__checkVat
#define soap_read__ns2__checkVat(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__checkVat(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__checkVat * SOAP_FMAC4 soap_get__ns2__checkVat(struct soap*, _ns2__checkVat *, const char*, const char*);

#define soap_new__ns2__checkVat(soap, n) soap_instantiate__ns2__checkVat(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__checkVat(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__checkVat * SOAP_FMAC2 soap_instantiate__ns2__checkVat(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__checkVat(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__checkVatApprox
#define SOAP_TYPE___ns1__checkVatApprox (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__checkVatApprox(struct soap*, struct __ns1__checkVatApprox *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__checkVatApprox(struct soap*, const struct __ns1__checkVatApprox *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__checkVatApprox(struct soap*, const char*, int, const struct __ns1__checkVatApprox *, const char*);
SOAP_FMAC3 struct __ns1__checkVatApprox * SOAP_FMAC4 soap_in___ns1__checkVatApprox(struct soap*, const char*, struct __ns1__checkVatApprox *, const char*);

#ifndef soap_write___ns1__checkVatApprox
#define soap_write___ns1__checkVatApprox(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__checkVatApprox(soap, data), 0) || soap_put___ns1__checkVatApprox(soap, data, "-ns1:checkVatApprox", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__checkVatApprox(struct soap*, const struct __ns1__checkVatApprox *, const char*, const char*);

#ifndef soap_read___ns1__checkVatApprox
#define soap_read___ns1__checkVatApprox(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__checkVatApprox(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__checkVatApprox * SOAP_FMAC4 soap_get___ns1__checkVatApprox(struct soap*, struct __ns1__checkVatApprox *, const char*, const char*);

#define soap_new___ns1__checkVatApprox(soap, n) soap_instantiate___ns1__checkVatApprox(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__checkVatApprox(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__checkVatApprox * SOAP_FMAC2 soap_instantiate___ns1__checkVatApprox(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__checkVatApprox(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__checkVat
#define SOAP_TYPE___ns1__checkVat (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__checkVat(struct soap*, struct __ns1__checkVat *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__checkVat(struct soap*, const struct __ns1__checkVat *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__checkVat(struct soap*, const char*, int, const struct __ns1__checkVat *, const char*);
SOAP_FMAC3 struct __ns1__checkVat * SOAP_FMAC4 soap_in___ns1__checkVat(struct soap*, const char*, struct __ns1__checkVat *, const char*);

#ifndef soap_write___ns1__checkVat
#define soap_write___ns1__checkVat(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__checkVat(soap, data), 0) || soap_put___ns1__checkVat(soap, data, "-ns1:checkVat", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__checkVat(struct soap*, const struct __ns1__checkVat *, const char*, const char*);

#ifndef soap_read___ns1__checkVat
#define soap_read___ns1__checkVat(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__checkVat(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__checkVat * SOAP_FMAC4 soap_get___ns1__checkVat(struct soap*, struct __ns1__checkVat *, const char*, const char*);

#define soap_new___ns1__checkVat(soap, n) soap_instantiate___ns1__checkVat(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__checkVat(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__checkVat * SOAP_FMAC2 soap_instantiate___ns1__checkVat(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__checkVat(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns2__checkVatApproxResponse
#define SOAP_TYPE_PointerTo_ns2__checkVatApproxResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__checkVatApproxResponse(struct soap*, _ns2__checkVatApproxResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__checkVatApproxResponse(struct soap*, const char *, int, _ns2__checkVatApproxResponse *const*, const char *);
SOAP_FMAC3 _ns2__checkVatApproxResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__checkVatApproxResponse(struct soap*, const char*, _ns2__checkVatApproxResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__checkVatApproxResponse
#define soap_write_PointerTo_ns2__checkVatApproxResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__checkVatApproxResponse(soap, data), 0) || soap_put_PointerTo_ns2__checkVatApproxResponse(soap, data, "ns2:checkVatApproxResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__checkVatApproxResponse(struct soap*, _ns2__checkVatApproxResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__checkVatApproxResponse
#define soap_read_PointerTo_ns2__checkVatApproxResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__checkVatApproxResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__checkVatApproxResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__checkVatApproxResponse(struct soap*, _ns2__checkVatApproxResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__checkVatApprox
#define SOAP_TYPE_PointerTo_ns2__checkVatApprox (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__checkVatApprox(struct soap*, _ns2__checkVatApprox *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__checkVatApprox(struct soap*, const char *, int, _ns2__checkVatApprox *const*, const char *);
SOAP_FMAC3 _ns2__checkVatApprox ** SOAP_FMAC4 soap_in_PointerTo_ns2__checkVatApprox(struct soap*, const char*, _ns2__checkVatApprox **, const char*);

#ifndef soap_write_PointerTo_ns2__checkVatApprox
#define soap_write_PointerTo_ns2__checkVatApprox(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__checkVatApprox(soap, data), 0) || soap_put_PointerTo_ns2__checkVatApprox(soap, data, "ns2:checkVatApprox", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__checkVatApprox(struct soap*, _ns2__checkVatApprox *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__checkVatApprox
#define soap_read_PointerTo_ns2__checkVatApprox(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__checkVatApprox(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__checkVatApprox ** SOAP_FMAC4 soap_get_PointerTo_ns2__checkVatApprox(struct soap*, _ns2__checkVatApprox **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__checkVatResponse
#define SOAP_TYPE_PointerTo_ns2__checkVatResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__checkVatResponse(struct soap*, _ns2__checkVatResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__checkVatResponse(struct soap*, const char *, int, _ns2__checkVatResponse *const*, const char *);
SOAP_FMAC3 _ns2__checkVatResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__checkVatResponse(struct soap*, const char*, _ns2__checkVatResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__checkVatResponse
#define soap_write_PointerTo_ns2__checkVatResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__checkVatResponse(soap, data), 0) || soap_put_PointerTo_ns2__checkVatResponse(soap, data, "ns2:checkVatResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__checkVatResponse(struct soap*, _ns2__checkVatResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__checkVatResponse
#define soap_read_PointerTo_ns2__checkVatResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__checkVatResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__checkVatResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__checkVatResponse(struct soap*, _ns2__checkVatResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__checkVat
#define SOAP_TYPE_PointerTo_ns2__checkVat (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__checkVat(struct soap*, _ns2__checkVat *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__checkVat(struct soap*, const char *, int, _ns2__checkVat *const*, const char *);
SOAP_FMAC3 _ns2__checkVat ** SOAP_FMAC4 soap_in_PointerTo_ns2__checkVat(struct soap*, const char*, _ns2__checkVat **, const char*);

#ifndef soap_write_PointerTo_ns2__checkVat
#define soap_write_PointerTo_ns2__checkVat(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__checkVat(soap, data), 0) || soap_put_PointerTo_ns2__checkVat(soap, data, "ns2:checkVat", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__checkVat(struct soap*, _ns2__checkVat *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__checkVat
#define soap_read_PointerTo_ns2__checkVat(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__checkVat(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__checkVat ** SOAP_FMAC4 soap_get_PointerTo_ns2__checkVat(struct soap*, _ns2__checkVat **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__matchCode
#define SOAP_TYPE_PointerTons2__matchCode (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__matchCode(struct soap*, enum ns2__matchCode *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__matchCode(struct soap*, const char *, int, enum ns2__matchCode *const*, const char *);
SOAP_FMAC3 enum ns2__matchCode ** SOAP_FMAC4 soap_in_PointerTons2__matchCode(struct soap*, const char*, enum ns2__matchCode **, const char*);

#ifndef soap_write_PointerTons2__matchCode
#define soap_write_PointerTons2__matchCode(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__matchCode(soap, data), 0) || soap_put_PointerTons2__matchCode(soap, data, "ns2:matchCode", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__matchCode(struct soap*, enum ns2__matchCode *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__matchCode
#define soap_read_PointerTons2__matchCode(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__matchCode(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum ns2__matchCode ** SOAP_FMAC4 soap_get_PointerTons2__matchCode(struct soap*, enum ns2__matchCode **, const char*, const char*);

#ifndef SOAP_TYPE_ns2__companyTypeCode
#define SOAP_TYPE_ns2__companyTypeCode (12)
#endif

#define soap_default_ns2__companyTypeCode(soap, a) soap_default_string(soap, a)


#define soap_serialize_ns2__companyTypeCode(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__companyTypeCode(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_ns2__companyTypeCode(struct soap*, const char*, char **, const char*);

#ifndef soap_write_ns2__companyTypeCode
#define soap_write_ns2__companyTypeCode(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__companyTypeCode(soap, data), 0) || soap_put_ns2__companyTypeCode(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__companyTypeCode(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_ns2__companyTypeCode
#define soap_read_ns2__companyTypeCode(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__companyTypeCode(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_ns2__companyTypeCode(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__date
#define SOAP_TYPE_xsd__date (7)
#endif

#define soap_default_xsd__date(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__date(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__date(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__date(struct soap*, const char*, char **, const char*);

#ifndef soap_write_xsd__date
#define soap_write_xsd__date(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__date(soap, data), 0) || soap_put_xsd__date(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__date(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_xsd__date
#define soap_read_xsd__date(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__date(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__date(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
