
CREATE TABLE  agenda  (
   Id  INTEGER NOT NULL  AUTO_INCREMENT ,
   dFecha  DATE  ,
   cHora  VARCHAR(45)    ,
   id_Usuario  int DEFAULT 0,
   cInicio  VARCHAR(6)  ,
   cFin  VARCHAR(6)  ,
   cAsunto  VARCHAR(40)    ,
   cDescripcionAsunto  VARCHAR(50)  ,
   cEstado  VARCHAR(50)    ,
   cAvisarTiempo  VARCHAR(50)    ,
   cImportancia  VARCHAR(50),
   PRIMARY KEY ( id ) );
   
   
   
   
CREATE TABLE  alb_pro  (
   Id  INTEGER NOT NULL AUTO_INCREMENT,
   cAlbaran  VARCHAR(50)    ,
   dFecha  DATE  ,
   id_Proveedor  int DEFAULT 0,
   cProveedor  VARCHAR(50)    ,
   cCifProveedor  VARCHAR(50)    ,
   rTotal1 NUMERIC(9,2) DEFAULT 0,
   rTotal2 NUMERIC(9,2) DEFAULT 0,
   rTotal3 NUMERIC(9,2) DEFAULT 0,
   rTotal4 NUMERIC(9,2) DEFAULT 0,
   nIva1 NUMERIC(9,2) DEFAULT 0,
   nIva2 NUMERIC(9,2) DEFAULT 0,
   nIva3 NUMERIC(9,2) DEFAULT 0,
   nIva4 NUMERIC(9,2) DEFAULT 0,
   rIva1 NUMERIC(9,2) DEFAULT 0,
   rIva2 NUMERIC(9,2) DEFAULT 0,
   rIva3 NUMERIC(9,2) DEFAULT 0,
   rIva4 NUMERIC(9,2) DEFAULT 0,
   rBase1 NUMERIC(9,2) DEFAULT 0,
   rBase2 NUMERIC(9,2) DEFAULT 0,
   rBase3 NUMERIC(9,2) DEFAULT 0,
   rBase4 NUMERIC(9,2) DEFAULT 0,
   cFactura  VARCHAR(50)    ,
   rBaseTotal NUMERIC(9,2) DEFAULT 0,
   rIvaTotal NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   tComentario  TEXT  ,
   nPedido  int DEFAULT 0,
   PRIMARY KEY (id) ); 
   
   
   

CREATE TABLE  articulos  (
   Id  INTEGER NOT NULL AUTO_INCREMENT,
   cCodigo  VARCHAR(50)    ,
   cCodigoBarras  VARCHAR(50)    ,
   cCodigoFabricante  VARCHAR(50)    ,
   cDescripcion  VARCHAR(50)    ,
   cDescripcionReducida  VARCHAR(50)    ,
   id_Proveedor  int DEFAULT 0,
   id_Familia  int DEFAULT 0,
   cFamilia  VARCHAR(50)    ,
   id_Seccion  int DEFAULT 0,
   cSeccion  VARCHAR(50)    ,
   id_Subfamilia  int DEFAULT 0,
   cSubfamilia  VARCHAR(50)    ,
   nTipoIva  NUMERIC(9,2) DEFAULT 0    ,
   rCoste NUMERIC(9,2) DEFAULT 0,
   rTarifa1 NUMERIC(9,2) DEFAULT 0,
   rTarifa2 NUMERIC(9,2) DEFAULT 0,
   rTarifa3 NUMERIC(9,2) DEFAULT 0,
   rDto NUMERIC(9,2) DEFAULT 0,
   nDtoProveedor NUMERIC(9,2) DEFAULT 0,
   nDtoproveedor2 NUMERIC(9,2) DEFAULT 0,
   nDtoProveedor3 NUMERIC(9,2) DEFAULT 0,
   dUltimaCompra  DATE  ,
   dUltimaVenta  DATE  ,
   nMargen1 NUMERIC(9,2) DEFAULT 0,
   nMargen2 NUMERIC(9,2) DEFAULT 0,
   nMargen3 NUMERIC(9,2) DEFAULT 0,
   rPrecioMedio NUMERIC(9,2) DEFAULT 0,
   rPrecioMedio2 NUMERIC(9,2) DEFAULT 0,
   rPrecioMedio3 NUMERIC(9,2) DEFAULT 0,
   nUnidadesCompradas  int DEFAULT 0,
   nUnidadesVendidas  int DEFAULT 0,
   rAcumuladoCompras NUMERIC(9,2) DEFAULT 0,
   rAcumuladoVentas NUMERIC(9,2) DEFAULT 0,
   bImagen  blob,
   tComentario  TEXT  ,
   nStockMaximo  int DEFAULT 0,
   nStockMinimo  int DEFAULT 0,
   nStockReal  int DEFAULT 0,
   cTipoUnidad  VARCHAR(50)    ,
   lControlarStock  int DEFAULT 0,
   cModelo  VARCHAR(50)    ,
   cTalla  VARCHAR(50)    ,
   cColor  VARCHAR(50)    ,
   cComposicion  VARCHAR(50)  ,
   lPvpIncluyeIva  int DEFAULT 0,
   dFechaPrevistaRecepcion  DATE,
   nCantidadPendienteRecibir  int DEFAULT 0,
   nReservados  int DEFAULT 0,
   lMostrarWeb  int DEFAULT 0,
   nEtiquetas  int DEFAULT 0,
   nPaquetes  int DEFAULT 0,
   cLocalizacion  VARCHAR(50),
   PRIMARY KEY ( id ) );
   
   
   

CREATE TABLE  FormPago  (
 id  integer NOT NULL AUTO_INCREMENT,
   cCodigo  VARCHAR(50)    ,
   cFormapago  VARCHAR(50)    ,
   nDiaPago1  int DEFAULT 0,
   nDiaPago2  int DEFAULT 0,
   nDiaPago3  int DEFAULT 0,
   nDiaPago4  int DEFAULT 0,
   nDias1  int DEFAULT 0,
   nDias2  int DEFAULT 0,
   nDias3  int DEFAULT 0,
   nDias4  int DEFAULT 0,
   PRIMARY KEY ( id ) );
   

CREATE TABLE  ObligacionesTrib  (
 id  integer NOT NULL AUTO_INCREMENT,
   cObligacion  VARCHAR(50)    ,
   dFecha  DATE  ,
   cModeloDocumento  VARCHAR(50)    ,
   cPeriodicidad  VARCHAR(50),
   PRIMARY KEY ( id ) );
   

   
   
DROP TABLE IF EXISTS  Secciones ;
CREATE TABLE  Secciones  (
 id  integer NOT NULL AUTO_INCREMENT,
   cSeccion  VARCHAR(50),
   PRIMARY KEY ( id ) );
   
   
   
CREATE TABLE  Sectores  (
 id  integer NOT NULL AUTO_INCREMENT,
   cSector  VARCHAR(50) ,
   PRIMARY KEY ( id ) );
   

CREATE TABLE  bancos  (
   Id  INTEGER NOT NULL AUTO_INCREMENT,
   cDescripcion  VARCHAR(50)    ,
   cEntidad  VARCHAR(50)    ,
   cOficina  VARCHAR(50)    ,
   cDc  VARCHAR(50)    ,
   cCuenta  VARCHAR(50)    ,
   rSaldo NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );
   
   
   
DROP TABLE IF EXISTS  cab_alb ;
CREATE TABLE  cab_alb  (
   Id  INTEGER NOT NULL AUTO_INCREMENT,
   nAlbaran  int DEFAULT 0,
   dFecha  DATE  ,
   cPedidoCli  VARCHAR(50)    ,
   id_Cliente  int DEFAULT 0,
   cCodigoCliente  VARCHAR(50)    ,
   cCliente  VARCHAR(50)    ,
   cDireccion  VARCHAR(50)    ,
   cDireccion2  VARCHAR(50)    ,
   cPoblacion  VARCHAR(50)    ,
   cProvincia  VARCHAR(50)    ,
   cCP  VARCHAR(50)    ,
   cPais  VARCHAR(50)    ,
   cCif  VARCHAR(50)    ,
   lRecargoEquivalencia  int DEFAULT 0,
   rSubtotal NUMERIC(9,2) DEFAULT 0,
   rDto NUMERIC(9,2) DEFAULT 0,
   nDto NUMERIC(9,2) DEFAULT 0,
   rBase1 NUMERIC(9,2) DEFAULT 0,
   rBase2 NUMERIC(9,2) DEFAULT 0,
   rBase3 NUMERIC(9,2) DEFAULT 0,
   rBase4 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIva1 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIva2 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIva3 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIva4 NUMERIC(9,2) DEFAULT 0,
   rImporteIva1 NUMERIC(9,2) DEFAULT 0,
   rImporteIva2 NUMERIC(9,2) DEFAULT 0,
   rImporteIva3 NUMERIC(9,2) DEFAULT 0,
   rImporteIva4 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeRecargoEq1 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeRecargoEq2 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeRecargoEq3 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeRecargoEq4 NUMERIC(9,2) DEFAULT 0,
   rImporteRecargoEq1 NUMERIC(9,2) DEFAULT 0,
   rImporteRecargoEq2 NUMERIC(9,2) DEFAULT 0,
   rImporteRecargoEq3 NUMERIC(9,2) DEFAULT 0,
   rImporteRecargoEq4 NUMERIC(9,2) DEFAULT 0,
   rTotal1 NUMERIC(9,2) DEFAULT 0,
   rTotal2 NUMERIC(9,2) DEFAULT 0,
   rTotal3 NUMERIC(9,2) DEFAULT 0,
   rTotal4 NUMERIC(9,2) DEFAULT 0,
   rBaseTotal NUMERIC(9,2) DEFAULT 0,
   rIvaTotal NUMERIC(9,2) DEFAULT 0,
   rRecargoEqTotal NUMERIC(9,2) DEFAULT 0,
   rTotalAlbaran NUMERIC(9,2) DEFAULT 0,
   lImpreso  int DEFAULT 0,
   lFacturado  int DEFAULT 0,
   cFactura  VARCHAR(45)    ,
   dFechaFactura  DATE  ,
   tComentario  TEXT,
   rACuenta NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );
   
CREATE TABLE  cab_fac  (
   Id  INTEGER NOT NULL AUTO_INCREMENT,
   cCodigoCliente  VARCHAR(50)    ,
   cFactura  VARCHAR(50)  ,
   dFecha  DATE  ,
   dFechaCobro  DATE  ,
   iId_Cliente  int DEFAULT 0,
   cCliente  VARCHAR(50)    ,
   cDireccion  VARCHAR(50)    ,
   cDireccion2  VARCHAR(50)    ,
   cCp  VARCHAR(50)    ,
   cPoblacion  VARCHAR(50)    ,
   cProvincia  VARCHAR(50)    ,
   cPais  VARCHAR(50)    ,
   cCif  VARCHAR(50)    ,
   lRecargoEquivalencia  int DEFAULT 0,
   rSubtotal NUMERIC(9,2) DEFAULT 0,
   nDto NUMERIC(9,2) DEFAULT 0,
   nDtoPP NUMERIC(9,2) DEFAULT 0,
   rImporteDescuento NUMERIC(9,2) DEFAULT 0,
   rImporteDescuentoPP NUMERIC(9,2) DEFAULT 0,
   rBase NUMERIC(9,2) DEFAULT 0,
   nIRPF NUMERIC(7,2) DEFAULT 0,
   rImporteIRPF NUMERIC(9,2) DEFAULT 0,
   nIva NUMERIC(9,2) DEFAULT 0,
   rImporteIva NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   lImpresa  int DEFAULT 0,
   lCobrada  int DEFAULT 0,
   lContabilizada  int DEFAULT 0,
   id_FormaPago  int DEFAULT 0,
   cFormaPago  VARCHAR(50)    ,
   tComentario  TEXT  ,
   rBase1 NUMERIC(9,2) DEFAULT 0,
   rBase2 NUMERIC(9,2) DEFAULT 0,
   rBase3 NUMERIC(9,2) DEFAULT 0,
   rBase4 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIVA1 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIVA2 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIVA3 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIVA4 NUMERIC(9,2) DEFAULT 0,
   rIVA1 NUMERIC(9,2) DEFAULT 0,
   rIVA2 NUMERIC(9,2) DEFAULT 0,
   rIVA3 NUMERIC(9,2) DEFAULT 0,
   rIVA4 NUMERIC(9,2) DEFAULT 0,
   rTotal1 NUMERIC(9,2) DEFAULT 0,
   rTotal2 NUMERIC(9,2) DEFAULT 0,
   rTotal3 NUMERIC(9,2) DEFAULT 0,
   rTotal4 NUMERIC(9,2) DEFAULT 0,
   nRec1 NUMERIC(9,2) DEFAULT 0,
   nRec2 NUMERIC(9,2) DEFAULT 0,
   nRec3 NUMERIC(9,2) DEFAULT 0,
   nRec4 NUMERIC(9,2) DEFAULT 0,
   rRecargoEq1 NUMERIC(9,2) DEFAULT 0,
   rRecargoEq2 NUMERIC(9,2) DEFAULT 0,
   rRecargoEq3 NUMERIC(9,2) DEFAULT 0,
   rRecargoEq4 NUMERIC(9,2) DEFAULT 0,
   rTotalRecargoEq NUMERIC(9,2) DEFAULT 0,
   rEntregadoaCuenta NUMERIC(9,2) DEFAULT 0,
   rImportePendiente NUMERIC(9,2) DEFAULT 0,
   cCodigoEntidad  VARCHAR(50)    ,
   cOficinaEntidad  VARCHAR(50)    ,
   cDCCuenta  VARCHAR(50)    ,
   cNumeroCuenta  VARCHAR(50)    ,
   cPedidoCliente  int DEFAULT 0,
   PRIMARY KEY ( id ) );
   
);

CREATE TABLE  cab_pre  (
   Id  INTEGER NOT NULL AUTO_INCREMENT,
   nPresupuesto  int DEFAULT 0,
   dFecha  DATE  ,
   dValidoHasta  DATE  ,
   id_Cliente  int DEFAULT 0,
   cCodigoCliente  VARCHAR(50)    ,
   cCliente  VARCHAR(50)    ,
   cCif  VARCHAR(50)    ,
   cDireccion  VARCHAR(50)    ,
   cDireccion2  VARCHAR(50)    ,
   cCP  VARCHAR(50)    ,
   cPoblacion  VARCHAR(50)    ,
   cProvincia  VARCHAR(50)    ,
   cPais  VARCHAR(50)    ,
   cTelefono  VARCHAR(50)    ,
   cMovil  VARCHAR(50)    ,
   cFax  VARCHAR(50)    ,
   nDto NUMERIC(9,2) DEFAULT 0,
   tComentarios  TEXT  ,
   rImporte NUMERIC(9,2) DEFAULT 0,
   rSubtotal NUMERIC(9,2) DEFAULT 0,
   rDescuento NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   lImpreso  int DEFAULT 0,
   lAprobado  int DEFAULT 0,
   dFechaAprobacion  DATE  ,
   rImporteFactura NUMERIC(9,2) DEFAULT 0,
   rImportePendiente NUMERIC(9,2) DEFAULT 0,
   cFactura  VARCHAR(50),
   nAlbaran  int DEFAULT 0,
   nPedido  int DEFAULT 0,
   id_FormaPago  int DEFAULT 0,
   cCodigoFormaPago  VARCHAR(50)    ,
   cDescripcionFormaPago  VARCHAR(50)    ,
   tLugarEntrega  TEXT  ,
   cAtencionde  VARCHAR(50)    ,
   rBase1 NUMERIC(9,2) DEFAULT 0,
   rBase2 NUMERIC(9,2) DEFAULT 0,
   rBase3 NUMERIC(9,2) DEFAULT 0,
   rBase4 NUMERIC(9,2) DEFAULT 0,
   nIva1 NUMERIC(9,2) DEFAULT 0,
   nIva2 NUMERIC(9,2) DEFAULT 0,
   nIva3 NUMERIC(9,2) DEFAULT 0,
   nIva4 NUMERIC(9,2) DEFAULT 0,
   rIva1 NUMERIC(9,2) DEFAULT 0,
   rIva2 NUMERIC(9,2) DEFAULT 0,
   rIva3 NUMERIC(9,2) DEFAULT 0,
   rIva4 NUMERIC(9,2) DEFAULT 0,
   nRecargoEquivalencia1 NUMERIC(9,2) DEFAULT 0,
   nRecargoEquivalencia2 NUMERIC(9,2) DEFAULT 0,
   nRecargoEquivalencia3 NUMERIC(9,2) DEFAULT 0,
   nRecargoEquivalencia4 NUMERIC(9,2) DEFAULT 0,
   rRec1 NUMERIC(9,2) DEFAULT 0,
   rRec2 NUMERIC(9,2) DEFAULT 0,
   rRec3 NUMERIC(9,2) DEFAULT 0,
   rRec4 NUMERIC(9,2) DEFAULT 0,
   rTotal1 NUMERIC(9,2) DEFAULT 0,
   rTotal2 NUMERIC(9,2) DEFAULT 0,
   rTotal3 NUMERIC(9,2) DEFAULT 0,
   rTotal4 NUMERIC(9,2) DEFAULT 0,
   lRecargoEquivalencia Int DEFAULT 0,
   cEmail VARCHAR(45),
   rTotalIva NUMERIC(9,2) DEFAULT 0,
   rTotalRec NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );
   

CREATE TABLE  cab_tpv  (
   Id  INTEGER NOT NULL AUTO_INCREMENT,
   nCaja  int DEFAULT 0,
   nTicket  int DEFAULT 0,
   dFecha  DATE  ,
   cHora  VARCHAR(50)    ,
   cUsuario  VARCHAR(50)    ,
   cNombreUsuario  VARCHAR(50)    ,
   id_Cliente  int DEFAULT 0,
   cCliente  VARCHAR(50)    ,
   cNombreCliente  VARCHAR(50)    ,
   lticketEnEpera  int DEFAULT 0,
   lPendienteCobro  int DEFAULT 0,
   cFormaPago  VARCHAR(50)    ,
   cTipoTarjeta  VARCHAR(50)    ,
   lImpreso  int DEFAULT 0,
   rImporte NUMERIC(9,2) DEFAULT 0,
   rBase1 NUMERIC(9,2) DEFAULT 0,
   rBase2 NUMERIC(9,2) DEFAULT 0,
   rBase3 NUMERIC(9,2) DEFAULT 0,
   rBase4 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIva1 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIva2 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIva3 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIva4 NUMERIC(9,2) DEFAULT 0,
   rImporteIva1 NUMERIC(9,2) DEFAULT 0,
   rImporteIva2 NUMERIC(9,2) DEFAULT 0,
   rImporteIva3 NUMERIC(9,2) DEFAULT 0,
   rImporteIva4 NUMERIC(9,2) DEFAULT 0,
   rTotal1 NUMERIC(9,2) DEFAULT 0,
   rTotal2 NUMERIC(9,2) DEFAULT 0,
   rTotal3 NUMERIC(9,2) DEFAULT 0,
   rTotal4 NUMERIC(9,2) DEFAULT 0,
   rSubotal NUMERIC(9,2) DEFAULT 0,
   rDto NUMERIC(9,2) DEFAULT 0,
   nPorcentajeRe1 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeRe2 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeRe3 NUMERIC(9,2) DEFAULT 0,
   nPorcentajeRe4 NUMERIC(9,2) DEFAULT 0,
   rImporteRecargoEq1 NUMERIC(9,2) DEFAULT 0,
   rImporteRecargoEq2 NUMERIC(9,2) DEFAULT 0,
   rImporteRecargoEq3 NUMERIC(9,2) DEFAULT 0,
   rImporteRecargoEq4 NUMERIC(9,2) DEFAULT 0,
   rTotalRecargoEq NUMERIC(9,2) DEFAULT 0,
   rImporteTotalIva NUMERIC(9,2) DEFAULT 0,
   rCobrado NUMERIC(9,2) DEFAULT 0,
   rPendienteCobro NUMERIC(9,2) DEFAULT 0,
   rImporteEfectivo NUMERIC(9,2) DEFAULT 0,
   rImporteTarjeta NUMERIC(9,2) DEFAULT 0,
   rImporteCheque NUMERIC(9,2) DEFAULT 0,
   rImporteCredito NUMERIC(9,2) DEFAULT 0,
   rImporteDtoRedondeo NUMERIC(9,2) DEFAULT 0,
   rImporteCambio NUMERIC(9,2) DEFAULT 0,
   rEntregado NUMERIC(9,2) DEFAULT 0,
   lPasadoAlbaranFactura  int DEFAULT 0,
   nNumeroAlbaran  int DEFAULT 0,
   nNumeroFactura  int DEFAULT 0,
   PRIMARY KEY ( id ) );
   
   
   
   
CREATE TABLE  cajaabierta  (
 id  integer NOT NULL AUTO_INCREMENT,
   dFechaAbertura  DATE  ,
   cHoraAbertura  VARCHAR(50)    ,
   nCaja  int DEFAULT 0,
   id_UsuarioAbertura  int DEFAULT 0,
   cUsuarioAbertura  VARCHAR(50)    ,
   id_UsuarioCierre  int DEFAULT 0,
   cUsuarioCierre  VARCHAR(50)    ,
   rImporteAbertura NUMERIC(9,2) DEFAULT 0,
   rImporteCierreAnterior NUMERIC(9,2) DEFAULT 0,
   lCajaCerrada  int DEFAULT 0,
   rMoneda NUMERIC(9,2) DEFAULT 0,
   rCheque NUMERIC(9,2) DEFAULT 0,
   rTarjeta NUMERIC(9,2) DEFAULT 0,
   rCredito NUMERIC(9,2) DEFAULT 0,
   rEntradasExtras NUMERIC(9,2) DEFAULT 0,
   rSalidasExtras NUMERIC(9,2) DEFAULT 0,
   rImportePendiente NUMERIC(9,2) DEFAULT 0,
   rVales NUMERIC(9,2) DEFAULT 0,
   rImporteCierre NUMERIC(9,2) DEFAULT 0,
   rValorRealCaja NUMERIC(9,2) DEFAULT 0,
   rDescuadre NUMERIC(9,2) DEFAULT 0,
   rImporteACuenta NUMERIC(9,2) DEFAULT 0,
   rImporteCambios NUMERIC(9,2) DEFAULT 0,
   rValesEmitidos NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );
   

CREATE TABLE  cierrecaja  (
 id  integer NOT NULL,
   dFechaCierre  DATE  ,
   rDeudas NUMERIC(9,2) DEFAULT 0,
   rEntregasACuenta NUMERIC(9,2) DEFAULT 0,
   rValesEmitidos NUMERIC(9,2) DEFAULT 0,
   lCajaCerrada  int DEFAULT 0,
   PRIMARY KEY ( id ) );
   
CREATE TABLE  clientes  (
   Id  INTEGER NOT NULL AUTO_INCREMENT,
   cCodigoCliente  VARCHAR(50)    ,
   cApellido1  VARCHAR(50)    ,
   cApellido2  VARCHAR(50)    ,
   cNombre  VARCHAR(50)    ,
   cNombreFiscal  VARCHAR(50)    ,
   cNombreComercial  VARCHAR(50)    ,
   cPersonaContacto  VARCHAR(50)    ,
   cCifNif  VARCHAR(50)    ,
   cDireccion1  VARCHAR(50)    ,
   cDireccion2  VARCHAR(50)    ,
   cCP  VARCHAR(50)    ,
   cPoblacion  VARCHAR(50)    ,
   cProvincia  VARCHAR(50)    ,
   cPais  VARCHAR(50)    ,
   cTelefono1  VARCHAR(50)    ,
   cTelefono2  VARCHAR(50)    ,
   cFax  VARCHAR(50)    ,
   cMovil  VARCHAR(50)    ,
   cEmail  VARCHAR(50)    ,
   cWeb  VARCHAR(50)    ,
   cDireccionFactura1  VARCHAR(50)    ,
   cDireccionFactura2  VARCHAR(50)    ,
   cCPFactura  VARCHAR(50)    ,
   cPoblacionFactura  VARCHAR(50)    ,
   cProvinciaFactura  VARCHAR(50)    ,
   cPaisFactura  VARCHAR(50)    ,
   cDireccionAlmacen  VARCHAR(50)    ,
   cDireccionAlmacen2  VARCHAR(50)    ,
   cCPAlmacen  VARCHAR(50)    ,
   cPoblacionAlmacen  VARCHAR(50)    ,
   cProvinciaAlmacen  VARCHAR(50)    ,
   cPaisAlmacen  VARCHAR(50)    ,
   dFechaAlta  DATE  ,
   dFechaUltimaCompra  DATE  ,
   rAcumuladoVentas NUMERIC(9,2) DEFAULT 0,
   rVentasEjercicio NUMERIC(9,2) DEFAULT 0,
   rRiesgoMaximo NUMERIC(9,2) DEFAULT 0,
   rDeudaActual NUMERIC(9,2) DEFAULT 0,
   tComentarios  TEXT  ,
   lBloqueado  int DEFAULT 0,
   tComentarioBloqueo  VARCHAR(50)  ,
   nPorcDtoCliente NUMERIC(9,2) DEFAULT 0,
   lRecargoEquivalencia  int DEFAULT 0,
   cCuentaContable  VARCHAR(50)    ,
   cCuentaIvaRepercutido  VARCHAR(50)    ,
   cCuentaDeudas  VARCHAR(50)    ,
   cCuentaCobros  VARCHAR(50)    ,
   cFormaPago  VARCHAR(50)    ,
   nDiapago1  int DEFAULT 0,
   nDiaPago2  int DEFAULT 0,
   nTarifaCliente  int DEFAULT 0,
   rImporteACuenta NUMERIC(9,2) DEFAULT 0,
   rVales NUMERIC(9,2) DEFAULT 0,
   cCentidadBancaria  VARCHAR(50)    ,
   cOficinaBancaria  VARCHAR(50)    ,
   cDC  VARCHAR(50)    ,
   cCuentaCorriente  VARCHAR(50)    ,
   dFechaNacimiento  DATE  ,
   rImportePendiente NUMERIC(9,2) DEFAULT 0,
   cTipoCliente  VARCHAR(50)  ,
   cAccesoWeb  VARCHAR(50)    ,
   cPasswordWeb  VARCHAR(50),
   nIRPF	INTEGER  DEFAULT 0,
   PRIMARY KEY ( id ) );

   
   CREATE TABLE  clientes_deuda  (
   id  integer NOT NULL AUTO_INCREMENT ,
   Id_Cliente  int DEFAULT 0,
   dFecha  DATE  ,
   dVencimiento  DATE  ,
   cDocumento  int DEFAULT 0,
   Id_Ticket  int DEFAULT 0,
   Id_Factura  int DEFAULT 0,
   nTipo  int DEFAULT 0,
   rImporte NUMERIC(9,2) DEFAULT 0,
   rPagado NUMERIC(9,2) DEFAULT 0,
   rPendienteCobro NUMERIC(9,2) DEFAULT 0,
   cEntidad  VARCHAR(50)    ,
   cOficina  VARCHAR(50)    ,
   cDC  VARCHAR(50)    ,
   cCuenta  VARCHAR(50),
   PRIMARY KEY ( id ) );

   
   CREATE TABLE  clientes_entregas  (
   id  integer NOT NULL AUTO_INCREMENT,
   Id_Cliente  int DEFAULT 0,
   dFecha  DATE  ,
   rImporte NUMERIC(9,2) DEFAULT 0,
   nDocumento  int DEFAULT 0,
   cTipo  VARCHAR(50),
   PRIMARY KEY ( id ) );

   
   CREATE TABLE  conceptostallas  (
   id  integer NOT NULL AUTO_INCREMENT,
   cConcepto  VARCHAR(50),
   PRIMARY KEY ( id ) );

CREATE TABLE  dependient  (
 id  integer NOT NULL AUTO_INCREMENT,
   cCodigo  VARCHAR(50)    ,
   cNombre  VARCHAR(50)    ,
   cDireccion  VARCHAR(50)    ,
   cCP  VARCHAR(50)    ,
   cPoblacion  VARCHAR(50)    ,
   cProvincia  VARCHAR(50)    ,
   dFechaNacimiento  DATE  ,
   cTelefono1  VARCHAR(50)    ,
   cTelefono2  VARCHAR(50)    ,
   cMovil  VARCHAR(50)    ,
   cNombrePariente  VARCHAR(50)    ,
   cPassword  VARCHAR(50)    ,
   rCosteHora NUMERIC(9,2) DEFAULT 0,
   rCosteHoraExtra NUMERIC(9,2) DEFAULT 0,
   dFechaAlta  DATE  ,
   dFinContrato  DATE  ,
   cCategoria  VARCHAR(50),
   PRIMARY KEY ( id ) );
   

CREATE TABLE  devoluciones  (
 id  integer NOT NULL AUTO_INCREMENT,
   nTicket  int DEFAULT 0,
   dFechaDevolucion  DATE  ,
   cAtendidoPor  VARCHAR(50)    ,
   id_Cliente  int DEFAULT 0,
   cCliente  VARCHAR(50)    ,
   tComentarios  TEXT  ,
   cCodArticulo  VARCHAR(50)    ,
   cDescArticulo  VARCHAR(50),
   PRIMARY KEY ( id ) );
   

CREATE TABLE  fac_pro  (
 id  integer NOT NULL AUTO_INCREMENT,
   cFactura  VARCHAR(50)    ,
   dFecha  DATE  ,
   dRecepcion  DATE  ,
   cPedido  VARCHAR(50)  ,
   Id_Proveedor  int DEFAULT 0,
   cProveedor  VARCHAR(50)    ,
   cCifProveedor  VARCHAR(50)    ,
   lRetencionIRPF  int DEFAULT 0,
   lRecargoEquivalencia  int DEFAULT 0,
   rBase1 NUMERIC(9,2) DEFAULT 0,
   rBase2 NUMERIC(9,2) DEFAULT 0,
   rBase3 NUMERIC(9,2) DEFAULT 0,
   rBase4 NUMERIC(9,2) DEFAULT 0,
   nPorcIva1 NUMERIC(9,2) DEFAULT 0,
   nPorcIva2 NUMERIC(9,2) DEFAULT 0,
   nPorcIva3 NUMERIC(9,2) DEFAULT 0,
   nPorcIva4 NUMERIC(9,2) DEFAULT 0,
   rIVA1 NUMERIC(9,2) DEFAULT 0,
   rIVA2 NUMERIC(9,2) DEFAULT 0,
   rIVA3 NUMERIC(9,2) DEFAULT 0,
   rIVA4 NUMERIC(9,2) DEFAULT 0,
   nREC1 NUMERIC(9,2) DEFAULT 0,
   nREC2 NUMERIC(9,2) DEFAULT 0,
   nREC3 NUMERIC(9,2) DEFAULT 0,
   nREC4 NUMERIC(9,2) DEFAULT 0,
   rREC1 NUMERIC(9,2) DEFAULT 0,
   rREC2 NUMERIC(9,2) DEFAULT 0,
   rREC3 NUMERIC(9,2) DEFAULT 0,
   rREC4 NUMERIC(9,2) DEFAULT 0,
   rTotal1 NUMERIC(9,2) DEFAULT 0,
   rTotal2 NUMERIC(9,2) DEFAULT 0,
   rTotal3 NUMERIC(9,2) DEFAULT 0,
   rTotal4 NUMERIC(9,2) DEFAULT 0,
   rTotalBase NUMERIC(9,2) DEFAULT 0,
   rTotalIVA NUMERIC(9,2) DEFAULT 0,
   rTotalRetencion NUMERIC(9,2) DEFAULT 0,
   rTotalRecargoEq NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   cFormaPago  VARCHAR(50)    ,
   nDiaPago1  numeric  ,
   nDiaPago2  numeric  ,
   nDiaPago3  numeric  ,
   nDiaPago4  numeric  ,
   rImportePagadoTotal NUMERIC(9,2) DEFAULT 0,
    Id_TipoGasto  int DEFAULT 0,
   cTipoGasto  VARCHAR(50)    ,
  tComentario  TEXT  ,
   lPagado  int DEFAULT 0,
   rImporteDeudaPendiente NUMERIC(9,2) DEFAULT 0,
   cCAlbaran  VARCHAR(50),
   PRIMARY KEY ( id ) );
   
CREATE TABLE  familias  (
 id  integer NOT NULL AUTO_INCREMENT,
   cCodigo  VARCHAR(50)    ,
   cFamilia  VARCHAR(50)    ,
   Id_Seccion  int DEFAULT 0,
   PRIMARY KEY ( id ) );
   

CREATE TABLE  histoart  (
 id  integer NOT NULL AUTO_INCREMENT,
   Id_Articulo  int DEFAULT 0,
   cCodigo  VARCHAR(50)    ,
   dFecha  DATE  ,
   nCantidad NUMERIC(9,2) DEFAULT 0,
   rImporte NUMERIC(9,2) DEFAULT 0  ,
   cNombreUsuario  VARCHAR(50),
   PRIMARY KEY ( id ) );
   
   
 CREATE TABLE  histovales  (
 id  integer NOT NULL AUTO_INCREMENT,
   nVale  int DEFAULT 0,
   dFecha  DATE  ,
   dVencimientoVale  DATE  ,
   cDependiente  VARCHAR(50)    ,
   rImporte NUMERIC(9,2) DEFAULT 0,
   Id_Ticket  int DEFAULT 0,
   Id_Cliente  int DEFAULT 0,
   cCliente  VARCHAR(50),
   PRIMARY KEY ( id ) );
   
   
   CREATE TABLE  lin_alb  (
 id  integer NOT NULL AUTO_INCREMENT,
   Id_Cab  int DEFAULT 0,
   cCodigo  VARCHAR(50)    ,
   nCantidad NUMERIC(9,2) DEFAULT 0,
   cDescripcion  VARCHAR(50)  ,
   rPvp NUMERIC(9,2) DEFAULT 0,
   rSubTotal NUMERIC(9,2) DEFAULT 0,
   rDto NUMERIC(9,2) DEFAULT 0,
   nDto NUMERIC(9,2) DEFAULT 0,
   nPorcIva NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );
   
CREATE TABLE  lin_alb_pro  (
 id  integer NOT NULL AUTO_INCREMENT,
   id_cab  int DEFAULT 0,
   cCodigo  VARCHAR(50),
   cDescripcion  VARCHAR(50),
   rCoste NUMERIC(9,2) DEFAULT 0,
   nDto NUMERIC(9,2) DEFAULT 0,
   rPvp1 NUMERIC(9,2) DEFAULT 0,
   rPvp2 NUMERIC(9,2) DEFAULT 0,
   rPvp3 NUMERIC(9,2) DEFAULT 0,
   nIva NUMERIC(9,2) DEFAULT 0,
   nCantidad NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   rDto NUMERIC(9,2) DEFAULT 0,
   rSUBTOTAL NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );

   
CREATE TABLE  lin_fac  (
 id  integer NOT NULL AUTO_INCREMENT,
   id_Cab  int DEFAULT 0,
   cCodigo  VARCHAR(50)    ,
   nCantidad NUMERIC(9,2) DEFAULT 0,
   cDescripcion  VARCHAR(50)  ,
   rPvp NUMERIC(9,2) DEFAULT 0,
   nDto NUMERIC(9,2) DEFAULT 0,
   rDto NUMERIC(9,2) DEFAULT 0,
   rSubTotal NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   nPorcIva NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );


   
CREATE TABLE  lin_fac_pro  (
 id  integer NOT NULL AUTO_INCREMENT,
   Id_Cab  int DEFAULT 0,
   cCodigo  VARCHAR(50)    ,
   cDescripcion  VARCHAR(50)    ,
   nCantidad NUMERIC(9,2) DEFAULT 0,
   rCosteBruto NUMERIC(9,2) DEFAULT 0,
   nPorcDto NUMERIC(9,2) DEFAULT 0,
   rDto NUMERIC(9,2) DEFAULT 0,
   rCoste NUMERIC(9,2) DEFAULT 0,
   nPorcIva NUMERIC(9,2) DEFAULT 0,
   rIva NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   nPedido  int DEFAULT 0,
   PRIMARY KEY ( id ) );
   
    CREATE TABLE  lin_ped   (
 id  integer NOT NULL AUTO_INCREMENT,
   Id_Cab  int DEFAULT 0,
   cCodigo  VARCHAR(50)    ,
   nCantidad NUMERIC(9,2) DEFAULT 0,
   cDescripcion  VARCHAR(50)  ,
   rPvp NUMERIC(9,2) DEFAULT 0,
   rSubTotal NUMERIC(9,2) DEFAULT 0,
   rDto NUMERIC(9,2) DEFAULT 0,
   nDto NUMERIC(9,2) DEFAULT 0,
   nPorcIva NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );  
   
CREATE TABLE  lin_ped_pro  (
 id  integer NOT NULL AUTO_INCREMENT,
   Id_Cab  int DEFAULT 0,
   Id_Articulo  int DEFAULT 0,
   cCodigo  VARCHAR(50)    ,
   cDescripcion  VARCHAR(50)  ,
   nCantidad NUMERIC(9,2) DEFAULT 0,
   rCosteBruto NUMERIC(9,2) DEFAULT 0,
   rSubtotal NUMERIC(9,2) DEFAULT 0,
   nPorcDto NUMERIC(9,2) DEFAULT 0,
   nDto NUMERIC(9,2) DEFAULT 0,
   nPorcIva NUMERIC(9,2) DEFAULT 0,
   rIVA NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   rTarifa1 NUMERIC(9,2) DEFAULT 0,
   nMargen1 NUMERIC(9,2) DEFAULT 0,
   rTarifa2 NUMERIC(9,2) DEFAULT 0,
   nMargen2 NUMERIC(9,2) DEFAULT 0,
   rTarifa3 NUMERIC(9,2) DEFAULT 0,
   nMargen3 NUMERIC(9,2) DEFAULT 0,
   nCantidadRecibida NUMERIC(9,2) DEFAULT 0,
   lRecibido  int DEFAULT 0,
   lTraspasado  int DEFAULT 0,
   cTalla  VARCHAR(50)    ,
   cColor  VARCHAR(50)    ,
   cCodigoInterno  VARCHAR(50)    ,
   nEtiquetas  int DEFAULT 0,
   lOK  int DEFAULT 0,
   PRIMARY KEY ( id ) );
   
   
CREATE TABLE  lin_pre  (
 id  integer NOT NULL AUTO_INCREMENT,
   Id_Cab  int DEFAULT 0,
   cCodigo  VARCHAR(50)    ,
   cDescripcion  VARCHAR(50)  ,
   nCantidad NUMERIC(9,2) DEFAULT 0,
   rPvp NUMERIC(9,2) DEFAULT 0,
   rSubTotal NUMERIC(9,2) DEFAULT 0,
   nPorcDto NUMERIC(9,2) DEFAULT 0,
   rDto NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   nPorcIVA NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );

   
   
CREATE TABLE  lin_res  (
 id  integer NOT NULL AUTO_INCREMENT,
   Id_Cab  int DEFAULT 0,
   cCodigo  VARCHAR(50)    ,
   cDescripcion  VARCHAR(50)    ,
   nCantidad  int DEFAULT 0,
   rImporte NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   Id_Cliente  int DEFAULT 0,
   cCliente  VARCHAR(50)    ,
   dFechaReserva  DATE  ,
   dReservadoHasta  DATE  ,
   nDto NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );

   
   
CREATE TABLE  lin_tpv  (
   Id  INTEGER NOT NULL AUTO_INCREMENT,
   id_Cab  int DEFAULT 0,
   id_Articulo  int DEFAULT 0,
   cCodigo  VARCHAR(50)    ,
   cDescripcion  VARCHAR(50)    ,
   rPvp NUMERIC(9,2) DEFAULT 0,
   nCantidad NUMERIC(9,2) DEFAULT 0,
   rImporte NUMERIC(9,2) DEFAULT 0,
   nPorcentajeIva NUMERIC(9,2) DEFAULT 0,
   nPorcDto NUMERIC(9,2) DEFAULT 0,
   nTotal NUMERIC(9,2) DEFAULT 0,
   cTipo  VARCHAR(50)    ,
   rSubTotal NUMERIC(9,2) DEFAULT 0,
   dFechaLinea  DATE,
   PRIMARY KEY ( id ) );
  
  
  

  CREATE TABLE ped_cli (
  Id int(11) NOT NULL AUTO_INCREMENT,
  nAlbaran int(11) DEFAULT '0',
  nPedido int(11) DEFAULT '0',
  dFecha date DEFAULT NULL,
  cPedido varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  id_Cliente int(11) DEFAULT '0',
  cCodigoCliente varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cCliente varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cDireccion varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cDireccion2 varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cPoblacion varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cProvincia varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cCP varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cPais varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cCif varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  lRecargoEquivalencia int(11) DEFAULT '0',
  rSubtotal decimal(9,2) DEFAULT '0.00',
  rDto decimal(9,2) DEFAULT '0.00',
  nDto decimal(9,2) DEFAULT '0.00',
  rBase1 decimal(9,2) DEFAULT '0.00',
  rBase2 decimal(9,2) DEFAULT '0.00',
  rBase3 decimal(9,2) DEFAULT '0.00',
  rBase4 decimal(9,2) DEFAULT '0.00',
  nPorcentajeIva1 decimal(9,2) DEFAULT '0.00',
  nPorcentajeIva2 decimal(9,2) DEFAULT '0.00',
  nPorcentajeIva3 decimal(9,2) DEFAULT '0.00',
  nPorcentajeIva4 decimal(9,2) DEFAULT '0.00',
  rImporteIva1 decimal(9,2) DEFAULT '0.00',
  rImporteIva2 decimal(9,2) DEFAULT '0.00',
  rImporteIva3 decimal(9,2) DEFAULT '0.00',
  rImporteIva4 decimal(9,2) DEFAULT '0.00',
  nPorcentajeRecargoEq1 decimal(9,2) DEFAULT '0.00',
  nPorcentajeRecargoEq2 decimal(9,2) DEFAULT '0.00',
  nPorcentajeRecargoEq3 decimal(9,2) DEFAULT '0.00',
  nPorcentajeRecargoEq4 decimal(9,2) DEFAULT '0.00',
  rImporteRecargoEq1 decimal(9,2) DEFAULT '0.00',
  rImporteRecargoEq2 decimal(9,2) DEFAULT '0.00',
  rImporteRecargoEq3 decimal(9,2) DEFAULT '0.00',
  rImporteRecargoEq4 decimal(9,2) DEFAULT '0.00',
  rTotal1 decimal(9,2) DEFAULT '0.00',
  rTotal2 decimal(9,2) DEFAULT '0.00',
  rTotal3 decimal(9,2) DEFAULT '0.00',
  rTotal4 decimal(9,2) DEFAULT '0.00',
  rBaseTotal decimal(9,2) DEFAULT '0.00',
  rIvaTotal decimal(9,2) DEFAULT '0.00',
  rRecargoEqTotal decimal(9,2) DEFAULT '0.00',
  rTotalAlbaran decimal(9,2) DEFAULT '0.00',
  lImpreso int(11) DEFAULT '0',
  lFacturado int(11) DEFAULT '0',
  cFactura varchar(45) COLLATE utf8_unicode_ci DEFAULT '0',
  dFechaFactura date DEFAULT NULL,
  tComentario text COLLATE utf8_unicode_ci,
  rACuenta decimal(9,2) DEFAULT '0.00',
  lTraspasadoAlb int(11) DEFAULT '0',
  lTraspasadoFac int(11) DEFAULT '0',
  cDireccionEntrega varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cDireccionEntrega2 varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cCPEntrega varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  cPoblacionEntrega varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cProvinciaEntrega varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  cPaisEntrega varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  lEnviado int Default '0',
  lCompleto int default '0',
  lEntregado int default '0',
  dFechaLimiteEntrega DATE, 
  PRIMARY KEY (Id));

  
  
  
  CREATE TABLE  ped_pro  (
 id  integer NOT NULL AUTO_INCREMENT,
   nPedido  int DEFAULT 0,
   cSerie  VARCHAR(50)    ,
   dFecha  DATE  ,
   dRecepcion  DATE  ,
   Id_Proveedor  int DEFAULT 0,
   cCodigoProveedor  VARCHAR(50)    ,
   cProveedor  VARCHAR(50)    ,
   cDireccion1  VARCHAR(50)    ,
   cDireccion2  VARCHAR(50)    ,
   cCP  VARCHAR(50)    ,
   cPoblacion  VARCHAR(50)    ,
   cProvincia  VARCHAR(50)    ,
   cPais  VARCHAR(50)    ,
   cCifNif  VARCHAR(50)    ,
   rBase NUMERIC(9,2) DEFAULT 0,
   rSubotal NUMERIC(9,2) DEFAULT 0,
   rDto NUMERIC(9,2) DEFAULT 0,
   nIVA NUMERIC(9,2) DEFAULT 0,
   rRecTotal NUMERIC(9,2) DEFAULT 0,
   rTotal NUMERIC(9,2) DEFAULT 0,
   lEnviado  int DEFAULT 0,
   lRecibido  int DEFAULT 0,
   lRecibidoCompleto  int DEFAULT 0,
   lGeneroPendiente  int DEFAULT 0,
   rBase1 NUMERIC(9,2) DEFAULT 0,
   rBase2 NUMERIC(9,2) DEFAULT 0,
   rBase3 NUMERIC(9,2) DEFAULT 0,
   rBase4 NUMERIC(9,2) DEFAULT 0,
   nPorcIva1 NUMERIC(9,2) DEFAULT 0,
   nPorcIva2 NUMERIC(9,2) DEFAULT 0,
   nPorcIva3 NUMERIC(9,2) DEFAULT 0,
   nPorcIva4 NUMERIC(9,2) DEFAULT 0,
   rIVA1 NUMERIC(9,2) DEFAULT 0,
   rIVA2 NUMERIC(9,2) DEFAULT 0,
   rIVA3 NUMERIC(9,2) DEFAULT 0,
   rIVA4 NUMERIC(9,2) DEFAULT 0,
   rTotal1 NUMERIC(9,2) DEFAULT 0,
   rTotal2 NUMERIC(9,2) DEFAULT 0,
   rTotal3 NUMERIC(9,2) DEFAULT 0,
   rTotal4 NUMERIC(9,2) DEFAULT 0,
   nMargenREC1 NUMERIC(9,2) DEFAULT 0,
   nMargenREC2 NUMERIC(9,2) DEFAULT 0,
   nMargenREC3 NUMERIC(9,2) DEFAULT 0,
   nMargenREC4 NUMERIC(9,2) DEFAULT 0,
   rREC1 NUMERIC(9,2) DEFAULT 0,
   rREC2 NUMERIC(9,2) DEFAULT 0,
   rREC3 NUMERIC(9,2) DEFAULT 0,
   rREC4 NUMERIC(9,2) DEFAULT 0,
   lTraspasado  int DEFAULT 0,
   nPedidoCliente  int DEFAULT 0,
   Id_FormaPago  int DEFAULT 0,
   cCodigoFormaPago  VARCHAR(50)    ,
   cFormaPago  VARCHAR(50)    ,
   dVencimiento1  DATE  ,
   dVencimiento2  DATE  ,
   dVencimiento3  DATE  ,
   dVencimiento4  DATE  ,
   lPagado1  int DEFAULT 0,
   lPagado2  int DEFAULT 0,
   lPagado3  int DEFAULT 0,
   lPagado4  int DEFAULT 0,
  tComentario  TEXT  ,
   dFechaEntrega  DATE  ,
   cDireccion1Entrega  VARCHAR(50)    ,
   cDireccion2Entrega  VARCHAR(50)    ,
   cCPEntrega  VARCHAR(50)    ,
   cPoblacionEntrega  VARCHAR(50)    ,
   cProvinciaEntrega  VARCHAR(50)    ,
   cPaisEntrega  VARCHAR(50)    ,
   cNombreCliente  VARCHAR(50)    ,
   cHorarioActivo  VARCHAR(50),  
   PRIMARY KEY ( id ) );
   
   
   
   
CREATE TABLE  proveedores  (
   Id  INTEGER NOT NULL AUTO_INCREMENT,
   cCodigo  int DEFAULT 0,
   cProveedor  VARCHAR(50)    ,
   cCif  VARCHAR(50)    ,
   cDireccion1  VARCHAR(50)    ,
   cDireccion2  VARCHAR(50)    ,
   cCP  VARCHAR(50)    ,
   cPoblacion  VARCHAR(50)    ,
   cProvincia  VARCHAR(50)    ,
   cPais  VARCHAR(50)    ,
   cTelefono1  VARCHAR(50)    ,
   cTelefono2  VARCHAR(50)    ,
   cTelefono3  VARCHAR(50)    ,
   cFax  VARCHAR(50)    ,
   cMovil  VARCHAR(50)    ,
   cEMail  VARCHAR(50)    ,
   cWeb  VARCHAR(50)    ,
   cPersonaContacto  VARCHAR(50)    ,
   nDiaCobro  int DEFAULT 0,
   cDireccionAlmacen  VARCHAR(50)    ,
   cCPAlmacen  VARCHAR(50)    ,
   cPoblacionAlmacen  VARCHAR(50)    ,
   cProvinciaAlmacen  VARCHAR(50)    ,
   cPaisAlmacen  VARCHAR(50)    ,
   cTelefonoAlmacen  VARCHAR(50)    ,
   cFaxAlmacen  VARCHAR(50)    ,
   cCodigoFormaPago  VARCHAR(50)    ,
   dFechaUltimaCompra  DATE  ,
   rAcumuladoCompras NUMERIC(9,2) DEFAULT 0,
   cEntidadBancariaProveedor  VARCHAR(50)    ,
   cOficinaBancariaProveedor  VARCHAR(50)    ,
   cDCProveedor  VARCHAR(50)    ,
   cCCProveedor  VARCHAR(50)    ,
   cEntidadPagoProveedor  VARCHAR(50)    ,
   cOficinaPagoProveedor  VARCHAR(50)    ,
   cDCPagoProveedor  VARCHAR(50)    ,
   cCuentaPagoProveedor  VARCHAR(50)    ,
   cCuentaIvaSoportado  VARCHAR(50)    ,
   rRetencionIRPF NUMERIC(9,2) DEFAULT 0,
   nTipoRetencion  int DEFAULT 0,
   cCuentaAplicacion  VARCHAR(50)    ,
   cCuentaPagos  VARCHAR(50)    ,
   tComentarios  TEXT  ,
   nDto NUMERIC(9,2) DEFAULT 0,
   dFechaAlta DATE  ,
   rDeudaMaxima NUMERIC(9,2) DEFAULT 0,
   rDeudaActual NUMERIC(9,2) DEFAULT 0,
   lRecargoEquivalencia  int DEFAULT 0,
   tTextoparaPedidos  TEXT,
   rEntregadoaCuenta DECIMAL(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );  

   
   
   
   
   
CREATE TABLE  recibos  (
   id  integer NOT NULL AUTO_INCREMENT,
   dFecha  DATE  ,
   dFechaCobro  DATE  ,
   cDescripcionFecha1  VARCHAR(50)    ,
   cDescripcionFecha2  VARCHAR(50)    ,
   cLocalidad  VARCHAR(50)    ,
   nRecibo  int DEFAULT 0,
   Id_Cliente  int DEFAULT 0,
   cCliente  VARCHAR(50)    ,
   cDireccion1  VARCHAR(50)    ,
   cDireccion2  VARCHAR(50)    ,
   cCp  VARCHAR(50)    ,
   cPoblacion  VARCHAR(50)    ,
   cProvincia  VARCHAR(50)    ,
   cPais  VARCHAR(50)    ,
   cConcepto  VARCHAR(50)    ,
   rImporte NUMERIC(9,2) DEFAULT 0,
   cImporte  VARCHAR(50)   ,
   cDescripcionEntidad  VARCHAR(50)    ,
   cDescripcionOficina  VARCHAR(50)    ,
   cEntidad  VARCHAR(50)    ,
   cOficina  VARCHAR(50)    ,
   cDC  VARCHAR(50)    ,
   cCuenta  VARCHAR(50)    ,
   lCobrado  int DEFAULT 0,
   PRIMARY KEY ( id ) );
   
   
   
   
   
CREATE TABLE  reservas  (
 id  integer NOT NULL AUTO_INCREMENT,
   nReserva  int DEFAULT 0,
   dFecha  DATE  ,
   id_cliente  int DEFAULT 0,
   cCliente  VARCHAR(50)    ,
   cDireccion  VARCHAR(50)    ,
   cDireccion2  VARCHAR(50)    ,
   cCP  VARCHAR(50)    ,
   cPoblacion  VARCHAR(50)    ,
   cProvincia  VARCHAR(50)    ,
   cPais  VARCHAR(50)    ,
   cTelefono1  VARCHAR(50)    ,
   cTelefono2  VARCHAR(50)    ,
   dFechaLimite  DATE  ,
   rImporte NUMERIC(9,2) DEFAULT 0,
   rPendiente NUMERIC(9,2) DEFAULT 0,
   rEntregado NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) );

   
   
   
   
CREATE TABLE  subfamilias  (
 id  integer NOT NULL AUTO_INCREMENT,
   cSubfamilia  VARCHAR(50)    ,
   Id_Familia  int DEFAULT 0,
   PRIMARY KEY ( id ) );

   
   
   
CREATE TABLE  tallas  (
 id  integer NOT NULL AUTO_INCREMENT,
   Talla  VARCHAR(50)    ,
   Id_ConceptoTalla  int DEFAULT 0,
   PRIMARY KEY ( id ) );
   

   
   
   CREATE TABLE  tareas  (
 id  integer NOT NULL AUTO_INCREMENT,
   cTarea  VARCHAR(50)    ,
   cAvisarA  VARCHAR(50)    ,
   nDiasFecha  int DEFAULT 0,
   lCobros  int DEFAULT 0,
   lPagos  int DEFAULT 0,
   lObligacionesTributarias  int DEFAULT 0,
   PRIMARY KEY ( id ) );

   
   
CREATE TABLE  tiposgasto  (
 id  integer NOT NULL AUTO_INCREMENT,
   cDescripcionTipoGasto  VARCHAR(50)    ,
   cComentario  VARCHAR(50),
   PRIMARY KEY ( id ) );


   
CREATE TABLE  tiposiva  (
 id  integer NOT NULL AUTO_INCREMENT,
   cTipo  VARCHAR(50)    ,
   cDescripcionTipoIVA  VARCHAR(50)    ,
   nIVA NUMERIC(9,2) DEFAULT 0,
   nRegargoEquivalencia NUMERIC(9,2) DEFAULT 0,
   PRIMARY KEY ( id ) ); 
   

   
CREATE TABLE  vales  (
 id  integer NOT NULL AUTO_INCREMENT,
   nNumero  int DEFAULT 0,
   cCodigo  VARCHAR(50)    ,
   dFecha  DATE  ,
   dVto  DATE  ,
   cDependient  VARCHAR(50)    ,
   rImporte NUMERIC(9,2) DEFAULT 0,
   IdTicket  int DEFAULT 0,
   Id_Cliente  int DEFAULT 0,
   cCliente  VARCHAR(50)    ,
   lPagado  int DEFAULT 0,
   PRIMARY KEY ( id ) );
   
