CREATE SCHEMA IF NOT EXISTS `@empresa@` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
CREATE TABLE `@empresa@`.`acum_articulos` (
  `id_articulo` int(11) NOT NULL,
  `unid_comp_enero` int(11) NOT NULL DEFAULT '0',
  `unid_comp_febrero` int(11) NOT NULL DEFAULT '0',
  `unid_comp_marzo` int(11) NOT NULL DEFAULT '0',
  `unid_comp_abril` int(11) NOT NULL DEFAULT '0',
  `unid_comp_mayo` int(11) NOT NULL DEFAULT '0',
  `unid_comp_junio` int(11) NOT NULL DEFAULT '0',
  `unid_comp_julio` int(11) NOT NULL DEFAULT '0',
  `unid_comp_agosto` int(11) NOT NULL DEFAULT '0',
  `unid_comp_septiembre` int(11) NOT NULL DEFAULT '0',
  `unid_comp_octubre` int(11) NOT NULL DEFAULT '0',
  `unid_comp_noviembre` int(11) NOT NULL DEFAULT '0',
  `unid_comp_diciembre` int(11) NOT NULL DEFAULT '0',
  `unid_comp_ejercicio` int(11) NOT NULL DEFAULT '0',
  `acum_comp_enero` double NOT NULL DEFAULT '0',
  `acum_comp_febrero` double NOT NULL DEFAULT '0',
  `acum_comp_marzo` double NOT NULL DEFAULT '0',
  `acum_comp_abril` double NOT NULL DEFAULT '0',
  `acum_comp_mayo` double NOT NULL DEFAULT '0',
  `acum_comp_junio` double NOT NULL DEFAULT '0',
  `acum_comp_julio` double NOT NULL DEFAULT '0',
  `acum_comp_agosto` double NOT NULL DEFAULT '0',
  `acum_comp_septiembre` double NOT NULL DEFAULT '0',
  `acum_comp_octubre` double NOT NULL DEFAULT '0',
  `acum_comp_noviembre` double NOT NULL DEFAULT '0',
  `acum_comp_diciembre` double NOT NULL DEFAULT '0',
  `acum_comp_ejercicio` double NOT NULL DEFAULT '0',
  `unid_vent_enero` double NOT NULL DEFAULT '0',
  `unid_vent_febrero` double NOT NULL DEFAULT '0',
  `unid_vent_marzo` double NOT NULL DEFAULT '0',
  `unid_vent_abril` double NOT NULL DEFAULT '0',
  `unid_vent_mayo` double NOT NULL DEFAULT '0',
  `unid_vent_junio` double NOT NULL DEFAULT '0',
  `unid_vent_julio` double NOT NULL DEFAULT '0',
  `unid_vent_agosto` double NOT NULL DEFAULT '0',
  `unid_vent_septiembre` double NOT NULL DEFAULT '0',
  `unid_vent_octubre` double NOT NULL DEFAULT '0',
  `unid_vent_noviembre` double NOT NULL DEFAULT '0',
  `unid_vent_diciembre` double NOT NULL DEFAULT '0',
  `unid_vent_acumulado` double NOT NULL DEFAULT '0',
  `acum_vent_enero` double NOT NULL DEFAULT '0',
  `acum_vent_febrero` double NOT NULL DEFAULT '0',
  `acum_vent_marzo` double NOT NULL DEFAULT '0',
  `acum_vent_abril` double NOT NULL DEFAULT '0',
  `acum_vent_mayo` double NOT NULL DEFAULT '0',
  `acum_vent_junio` double NOT NULL DEFAULT '0',
  `acum_vent_julio` double NOT NULL DEFAULT '0',
  `acum_vent_agosto` double NOT NULL DEFAULT '0',
  `acum_vent_septiembre` double NOT NULL DEFAULT '0',
  `acum_vent_octubre` double NOT NULL DEFAULT '0',
  `acum_vent_noviembre` double NOT NULL DEFAULT '0',
  `acum_vent_diciembre` double NOT NULL DEFAULT '0',
  `acum_vent_ejercicio` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_articulo`),
  UNIQUE KEY `id_Articulo_UNIQUE` (`id_articulo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`acum_clientes` (
  `id_cliente` int(11) NOT NULL DEFAULT '0',
  `acum_enero` double NOT NULL DEFAULT '0',
  `acum_febrero` double NOT NULL DEFAULT '0',
  `acum_marzo` double NOT NULL DEFAULT '0',
  `acum_abril` double NOT NULL DEFAULT '0',
  `acum_mayo` double NOT NULL DEFAULT '0',
  `acum_junio` double NOT NULL DEFAULT '0',
  `acum_julio` double NOT NULL DEFAULT '0',
  `acum_agosto` double NOT NULL DEFAULT '0',
  `acum_septiembre` double NOT NULL DEFAULT '0',
  `acum_octubre` double NOT NULL DEFAULT '0',
  `acum_noviembre` double NOT NULL DEFAULT '0',
  `acum_diciembre` double NOT NULL DEFAULT '0',
  `acum_ejercicio` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_cliente`),
  UNIQUE KEY `Id_Cliente_UNIQUE` (`id_cliente`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`acum_proveedores` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_proveedor` int(11) DEFAULT NULL,
  `acum_enero` double DEFAULT NULL,
  `acum_febrero` double DEFAULT NULL,
  `acum_marzo` double DEFAULT NULL,
  `acum_abril` double DEFAULT NULL,
  `acum_mayo` double DEFAULT NULL,
  `acum_junio` double DEFAULT NULL,
  `acum_julio` double DEFAULT NULL,
  `acum_agosto` double DEFAULT NULL,
  `acum_septiembre` double DEFAULT NULL,
  `acum_octubre` double DEFAULT NULL,
  `acum_noviembre` double DEFAULT NULL,
  `acum_diciembre` double DEFAULT NULL,
  `acum_total` double DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`alb_pro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `albaran` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `id_proveedor` int(11) DEFAULT '0',
  `proveedor` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cif_proveedor` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `total1` double DEFAULT '0',
  `total2` double DEFAULT '0',
  `total3` double DEFAULT '0',
  `total4` double DEFAULT '0',
  `porc_iva1` float DEFAULT '0',
  `porc_iva2` float DEFAULT '0',
  `porc_iva3` float DEFAULT '0',
  `porc_iva4` float DEFAULT '0',
  `iva1` double DEFAULT '0',
  `iva2` double DEFAULT '0',
  `iva3` double DEFAULT '0',
  `iva4` double DEFAULT '0',
  `base1` double DEFAULT '0',
  `base2` double DEFAULT '0',
  `base3` double DEFAULT '0',
  `base4` double DEFAULT '0',
  `factura` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `base_total` double DEFAULT '0',
  `iva_total` double DEFAULT '0',
  `total` double DEFAULT '0',
  `comentario` text COLLATE utf8_unicode_ci,
  `pedido` int(11) DEFAULT '0',
  `recargo_equivalencia` tinyint(1) DEFAULT NULL,
  `porc_rec1` float DEFAULT NULL,
  `porc_rec2` float DEFAULT NULL,
  `porc_rec3` float DEFAULT NULL,
  `porc_rec4` float DEFAULT NULL,
  `rec1` double DEFAULT NULL,
  `rec2` double DEFAULT NULL,
  `rec3` double DEFAULT NULL,
  `rec4` double DEFAULT NULL,
  `importe_rec_total` double DEFAULT NULL,
  `ejercicio` int(5) DEFAULT NULL,
  `subtotal` double DEFAULT NULL,
  `direccion1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais` int(11) DEFAULT NULL,
  `dto` float DEFAULT NULL,
  `telefono` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `movil` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `codigo_proveedor` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_forma_pago` int(11) DEFAULT '0',
  `impreso` tinyint(1) DEFAULT '0',
  `desc_gasto1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto3` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `imp_gasto1` double DEFAULT '0',
  `imp_gasto2` double DEFAULT '0',
  `imp_gasto3` double DEFAULT '0',
  `porc_iva_gasto1` float DEFAULT '0',
  `porc_iva_gasto2` float DEFAULT '0',
  `porc_iva_gasto3` float DEFAULT '0',
  `iva_gasto1` float DEFAULT '0',
  `iva_gasto2` float DEFAULT '0',
  `iva_gasto3` float DEFAULT '0',
  `gasto_to_coste` tinyint(1) DEFAULT '0',
  `editable` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`articulos_excepciones` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion` varchar(100) DEFAULT NULL,
  `id_articulo` int(11) DEFAULT NULL,
  `id_familia` int(11) DEFAULT NULL,
  `id_cliente` int(11) DEFAULT NULL,
  `id_familia_cliente` int(11) DEFAULT NULL,
  `id_subfamilia_cliente` int(11) DEFAULT NULL,
  `id_proveedor` int(11) DEFAULT NULL,
  `id_agente` int(11) DEFAULT NULL,
  `importe_porc_aumento` double DEFAULT '0',
  `importe_moneda_aumento` double DEFAULT '0',
  `importe_fijo` double DEFAULT '0',
  `dto_aumento_fijo` double DEFAULT '0',
  `dto_aumento_porc` double DEFAULT '0',
  `dto_fijo` double DEFAULT '0',
  `fecha_inicio` date DEFAULT NULL,
  `fecha_final` date DEFAULT NULL,
  `id_aviso_ini` int(11) DEFAULT NULL,
  `id_aviso_fin` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
CREATE TABLE `@empresa@`.`articulos_ofertas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_articulo` int(11) DEFAULT NULL,
  `descripcion` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `oferta_32` tinyint(4) DEFAULT NULL,
  `oferta_dto` tinyint(4) DEFAULT NULL,
  `oferta_precio_final` tinyint(4) DEFAULT NULL,
  `oferta_web` tinyint(4) DEFAULT NULL,
  `unidades` float DEFAULT NULL,
  `regalo` float DEFAULT NULL,
  `dto_local` float DEFAULT NULL,
  `dto_web` float DEFAULT NULL,
  `precio_final` double DEFAULT NULL,
  `comentarios` text COLLATE utf8_unicode_ci,
  `fecha_inicio` date DEFAULT NULL,
  `fecha_fin` date DEFAULT NULL,
  `activa` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`cab_alb` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `serie` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `albaran` int(11) DEFAULT '0',
  `id_divisa` int(11) DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `pedido_cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_cliente` int(11) DEFAULT '0',
  `codigo_cliente` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais` int(11) DEFAULT NULL,
  `direccion1_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion2_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia_entrega` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp_entrega` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais_entrega` int(11) DEFAULT NULL,
  `email_entrega` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `comentarios_entrega` text COLLATE utf8_unicode_ci,
  `cif` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `telefono` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `movil` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `recargo_equivalencia` tinyint(1) DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `dto` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `porc_dto_pp` float DEFAULT '0',
  `dto_pp` float DEFAULT '0',
  `base1` double DEFAULT '0',
  `base2` double DEFAULT '0',
  `base3` double DEFAULT '0',
  `base4` double DEFAULT '0',
  `porc_iva1` float DEFAULT '0',
  `porc_iva2` float DEFAULT '0',
  `porc_iva3` float DEFAULT '0',
  `porc_iva4` float DEFAULT '0',
  `iva1` double DEFAULT '0',
  `iva2` double DEFAULT '0',
  `iva3` double DEFAULT '0',
  `iva4` double DEFAULT '0',
  `porc_rec1` float DEFAULT '0',
  `porc_rec2` float DEFAULT '0',
  `porc_rec3` float DEFAULT '0',
  `porc_rec4` float DEFAULT '0',
  `rec1` double DEFAULT '0',
  `rec2` double DEFAULT '0',
  `rec3` double DEFAULT '0',
  `rec4` double DEFAULT '0',
  `total1` double DEFAULT '0',
  `total2` double DEFAULT '0',
  `total3` double DEFAULT '0',
  `total4` double DEFAULT '0',
  `base_total` double DEFAULT '0',
  `iva_total` double DEFAULT '0',
  `rec_total` double DEFAULT '0',
  `total_albaran` double DEFAULT '0',
  `impreso` tinyint(1) DEFAULT '0',
  `facturado` tinyint(1) DEFAULT '0',
  `factura` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fecha_factura` date DEFAULT NULL,
  `comentario` text COLLATE utf8_unicode_ci,
  `entregado_a_cuenta` double DEFAULT '0',
  `id_forma_pago` int(11) DEFAULT '0',
  `desc_gasto1` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto2` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto3` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `imp_gasto1` double DEFAULT NULL,
  `imp_gasto2` double DEFAULT NULL,
  `imp_gasto3` double DEFAULT NULL,
  `porc_iva_gasto1` float DEFAULT '0',
  `porc_iva_gasto2` float DEFAULT '0',
  `porc_iva_gasto3` float DEFAULT '0',
  `iva_gasto1` float DEFAULT '0',
  `iva_gasto2` float DEFAULT '0',
  `iva_gasto3` float DEFAULT '0',
  `id_transportista` int(11) DEFAULT '0',
  `ejercicio` int(5) DEFAULT NULL,
  `editable` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`cab_fac` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `codigo_cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `serie` char(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `factura` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_divisa` int(11) DEFAULT NULL,
  `tarifa_cliente` INT NULL DEFAULT '1', 
  `fecha` date DEFAULT NULL,
  `fecha_cobro` date DEFAULT NULL,
  `id_cliente` int(11) NOT NULL DEFAULT '0',
  `cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais` int(11) DEFAULT NULL,
  `direccion1_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion2_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia_entrega` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp_entrega` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais_entrega` int(11) DEFAULT NULL,
  `email_entrega` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
  `comentarios_entrega` text COLLATE utf8_unicode_ci NOT NULL,
  `cif` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `telefono` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `movil` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `recargo_equivalencia` tinyint(1) DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `porc_dto_pp` float DEFAULT '0',
  `dto` double DEFAULT '0',
  `dto_pp` double DEFAULT '0',
  `base` double DEFAULT '0',
  `porc_irpf` float DEFAULT '0',
  `irpf` double DEFAULT '0',
  `iva` double DEFAULT '0',
  `total` double DEFAULT '0',
  `impreso` tinyint(1) DEFAULT '0',
  `cobrado` tinyint(1) DEFAULT '0',
  `contabilizado` tinyint(1) DEFAULT '0',
  `id_forma_pago` int(11) DEFAULT '0',
  `forma_pago` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `comentario` text COLLATE utf8_unicode_ci,
  `base1` double DEFAULT '0',
  `base2` double DEFAULT '0',
  `base3` double DEFAULT '0',
  `base4` double DEFAULT '0',
  `porc_iva1` float DEFAULT '0',
  `porc_iva2` float DEFAULT '0',
  `porc_iva3` float DEFAULT '0',
  `porc_iva4` float DEFAULT '0',
  `iva1` double DEFAULT '0',
  `iva2` double DEFAULT '0',
  `iva3` double DEFAULT '0',
  `iva4` double DEFAULT '0',
  `total1` double DEFAULT '0',
  `total2` double DEFAULT '0',
  `total3` double DEFAULT '0',
  `total4` double DEFAULT '0',
  `porc_rec1` float DEFAULT '0',
  `porc_rec2` float DEFAULT '0',
  `porc_rec3` float DEFAULT '0',
  `porc_rec4` float DEFAULT '0',
  `rec1` double DEFAULT '0',
  `rec2` double DEFAULT '0',
  `rec3` double DEFAULT '0',
  `rec4` double DEFAULT '0',
  `total_recargo` double DEFAULT '0',
  `entregado_a_cuenta` double DEFAULT '0',
  `importe_pendiente` double DEFAULT '0',
  `codigo_entidad` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `oficina_entidad` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dc_cuenta` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cuenta_corriente` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pedido_cliente` int(11) DEFAULT '0',
  `desc_gasto1` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto2` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto3` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `imp_gasto1` double DEFAULT NULL,
  `imp_gasto2` double DEFAULT NULL,
  `imp_gasto3` double DEFAULT NULL,
  `porc_iva_gasto1` float DEFAULT '0',
  `porc_iva_gasto2` float DEFAULT '0',
  `porc_iva_gasto3` float DEFAULT '0',
  `iva_gasto1` float DEFAULT '0',
  `iva_gasto2` float DEFAULT '0',
  `iva_gasto3` float DEFAULT '0',
  `asiento` int(11) DEFAULT NULL,
  `id_transportista` int(11) DEFAULT '0',
  `ejercicio` int(5) DEFAULT NULL,
  `editable` tinyint(1) DEFAULT '1',
  `efectivo` double DEFAULT '0',
  `transferencia` double DEFAULT '0',
  `tarjeta` double DEFAULT '0',
  `cheque` double NOT NULL DEFAULT '0',
  `internet` double NOT NULL DEFAULT '0',
  `pagado` double NOT NULL DEFAULT '0',
  `pendiente` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`,`id_cliente`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`cab_pre` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `presupuesto` int(11) DEFAULT '0',
  `id_divisa` int(11) NOT NULL DEFAULT '1',
  `fecha` date DEFAULT NULL,
  `valido_hasta` date DEFAULT NULL,
  `codigo_cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_cliente` int(11) DEFAULT '-1',
  `cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cif` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais` int(11) DEFAULT NULL,
  `direccion1_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion2_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia_entrega` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp_entrega` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais_entrega` int(11) DEFAULT NULL,
  `email_entrega` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `comentarios_entrega` text COLLATE utf8_unicode_ci,
  `telefono` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `movil` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dto` decimal(9,2) DEFAULT '0.00',
  `comentarios` text COLLATE utf8_unicode_ci,
  `importe` double DEFAULT '0',
  `base` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `total` double DEFAULT '0',
  `impreso` tinyint(1) DEFAULT '0',
  `aprobado` tinyint(1) DEFAULT '0',
  `fecha_aprobacion` date DEFAULT NULL,
  `importe_factura` double DEFAULT '0',
  `importe_pendiente` double DEFAULT '0',
  `factura` varchar(25) COLLATE utf8_unicode_ci DEFAULT '0',
  `albaran` int(11) DEFAULT '0',
  `pedido` int(11) DEFAULT '0',
  `id_forma_pago` int(11) DEFAULT '0',
  `lugar_entrega` text COLLATE utf8_unicode_ci,
  `atencion_de` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `base1` double DEFAULT '0',
  `base2` double DEFAULT '0',
  `base3` double DEFAULT '0',
  `base4` double DEFAULT '0',
  `porc_iva1` float DEFAULT '0',
  `porc_iva2` float DEFAULT '0',
  `porc_iva3` float DEFAULT '0',
  `porc_iva4` float DEFAULT '0',
  `iva1` double DEFAULT '0',
  `iva2` double DEFAULT '0',
  `iva3` double DEFAULT '0',
  `iva4` double DEFAULT '0',
  `porc_rec1` float DEFAULT '0',
  `porc_rec2` float DEFAULT '0',
  `porc_rec3` float DEFAULT '0',
  `porc_rec4` float DEFAULT '0',
  `rec1` double DEFAULT '0',
  `rec2` double DEFAULT '0',
  `rec3` double DEFAULT '0',
  `rec4` double DEFAULT '0',
  `total1` double DEFAULT '0',
  `total2` double DEFAULT '0',
  `total3` double DEFAULT '0',
  `total4` double DEFAULT '0',
  `recargo_equivalencia` tinyint(1) DEFAULT '0',
  `email` varchar(70) COLLATE utf8_unicode_ci DEFAULT NULL,
  `total_iva` double DEFAULT '0',
  `total_recargo` double DEFAULT '0',
  `porc_dto_pp` float DEFAULT '0',
  `dto_pp` double DEFAULT '0',
  `gastos_distribuidos1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `gastos_distribuidos2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `gastos_distribuidos3` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `importe_gasto1` double DEFAULT '0',
  `importe_gasto2` double DEFAULT '0',
  `importe_gasto3` double DEFAULT '0',
  `porc_iva_gasto1` float DEFAULT '0',
  `porc_iva_gasto2` float DEFAULT '0',
  `porc_iva_gasto3` float DEFAULT '0',
  `iva_gasto1` float DEFAULT '0',
  `iva_gasto2` float DEFAULT '0',
  `iva_gasto3` float DEFAULT '0',
  `ejercicio` int(5) DEFAULT NULL,
  `editable` tinyint(1) DEFAULT '1',
  `valor_divisa` float NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`cab_tpv` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `caja` int(11) DEFAULT '0',
  `serie` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ticket` int(11) DEFAULT '0',
  `fecha` date NOT NULL,
  `hora` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `id_usuario` int(11) DEFAULT NULL,
  `id_cliente` int(11) DEFAULT '0',
  `codigo_` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nombre_cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ticket_en_espera` tinyint(1) DEFAULT '0',
  `pendiente_cobro` tinyint(1) DEFAULT '0',
  `id_forma_pago` int(11) DEFAULT '0',
  `tipo_targeta` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `impreso` tinyint(1) DEFAULT '0',
  `importe` double DEFAULT '0',
  `base1` double DEFAULT '0',
  `base2` double DEFAULT '0',
  `base3` double DEFAULT '0',
  `base4` double DEFAULT '0',
  `porc_iva1` float DEFAULT '0',
  `porc_iva2` float DEFAULT '0',
  `porc_iva3` float DEFAULT '0',
  `porc_iva4` float DEFAULT '0',
  `iva1` double DEFAULT '0',
  `iva2` double DEFAULT '0',
  `iva3` double DEFAULT '0',
  `iva4` double DEFAULT '0',
  `total1` double DEFAULT '0',
  `total2` double DEFAULT '0',
  `total3` double DEFAULT '0',
  `total4` double DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `dto` double DEFAULT '0',
  `total_iva` double DEFAULT '0' COMMENT '	',
  `cobrado` double DEFAULT '0',
  `importe_pendiente_cobro` double DEFAULT '0',
  `importe_efectivo` double DEFAULT '0',
  `importe_tarjeta` double DEFAULT '0',
  `importe_cheque` double DEFAULT '0',
  `importe_domiciliacion` double DEFAULT '0',
  `importe_vale` double DEFAULT NULL,
  `importe_dto_redondeo` double DEFAULT '0',
  `importe_cambio` double DEFAULT '0',
  `entregado_a_cuenta` double DEFAULT '0',
  `numero_pedido` int(11) NOT NULL DEFAULT '0',
  `numero_albaran` int(11) DEFAULT '0',
  `numero_factura` int(11) DEFAULT '0',
  `id_cierre` int(11) DEFAULT NULL,
  `ejercicio` int(5) DEFAULT NULL,
  `editable` tinyint(1) DEFAULT '1',
  `importe_transferencia` double DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`cajas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `desc_caja` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`cierrecaja` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fecha_abertura` date DEFAULT NULL,
  `fecha_cierre` date DEFAULT NULL,
  `hora_abertura` time DEFAULT NULL,
  `hora_cierre` time DEFAULT NULL,
  `vales_emitidos` double DEFAULT NULL,
  `entregas_a_cuenta` double DEFAULT NULL,
  `intresos_efectivo` double DEFAULT NULL,
  `ingresos_tarjetas` double DEFAULT NULL,
  `ingresos_cheques` double DEFAULT NULL,
  `ingresos_credito` double DEFAULT NULL,
  `ingresos_extraordinarios` double DEFAULT NULL,
  `importe_abertura_dia` double DEFAULT NULL,
  `importe_cierre` double DEFAULT NULL,
  `id_usuario` int(11) DEFAULT NULL,
  `id_usuario_cierre` int(11) DEFAULT NULL,
  `importe_real_caja` double DEFAULT NULL,
  `descuadre` double DEFAULT NULL,
  `descuentos` double DEFAULT NULL,
  `beneficio_bruto` double DEFAULT NULL,
  `id_caja` int(11) DEFAULT NULL,
  `ingresos_vales` double DEFAULT NULL,
  `gastos_caja` double DEFAULT NULL,
  `ejercicio` int(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`clientes_deuda` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cliente` int(11) DEFAULT '0',
  `fecha` date DEFAULT NULL,
  `vencimiento` date DEFAULT NULL,
  `documento` int(11) DEFAULT '0',
  `id_ticket` int(11) DEFAULT '0',
  `id_factura` int(11) DEFAULT '0',
  `tipo` int(11) DEFAULT '0',
  `importe` double DEFAULT '0',
  `pagado` double DEFAULT '0',
  `pendiente_cobro` double DEFAULT '0',
  `entidad` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `oficina_entidad` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dc_cuenta` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cuenta_corriente` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `importe_efectivo` double DEFAULT NULL,
  `importe_tarjeta` double DEFAULT NULL,
  `importe_cheque` double DEFAULT NULL,
  `importe_transferencia` double DEFAULT NULL,
  `importe_internet` double DEFAULT NULL,
  `importe_vale` double DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`desglose_caja` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cierre` int(11) DEFAULT NULL,
  `nombre_moneda` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cantidad` int(11) DEFAULT NULL,
  `importe` double DEFAULT NULL,
  `id_moneda` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`deudas_proveedores` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '	',
  `id_documento` int(11) DEFAULT NULL,
  `documento` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fecha_deuda` date DEFAULT NULL,
  `vencimiento` date DEFAULT NULL,
  `importe_deuda` double DEFAULT NULL,
  `pago_por` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `numero_tarjeta_cuenta` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_proveedor` int(11) DEFAULT NULL,
  `pendiente` double DEFAULT NULL,
  `id_asiento` int(11) DEFAULT NULL,
  `asiento_numero` int(11) DEFAULT NULL,
  `pagado` double DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`devoluciones` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ticket` int(11) DEFAULT '0',
  `fecha_devolucion` datetime DEFAULT NULL,
  `atendido_por` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_cliente` int(11) DEFAULT '0',
  `cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `comentarios` text COLLATE utf8_unicode_ci,
  `codigo_articulo` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `descripcion` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_articulo` int(11) DEFAULT NULL,
  `ejercicio` int(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`e_s_caja` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `concepto` text COLLATE utf8_unicode_ci,
  `id_usuario` int(11) DEFAULT NULL,
  `importe` double DEFAULT '0',
  `fecha` date DEFAULT NULL,
  `hora` time DEFAULT NULL,
  `entrada` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`fac_pro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `factura` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `fecha_recepcion` date DEFAULT NULL,
  `pedido` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_proveedor` int(11) DEFAULT '0',
  `proveedor` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cif_proveedor` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais` int(11) DEFAULT NULL,
  `telefono` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `movil` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dto` decimal(9,2) DEFAULT '0.00',
  `retencion_irpf` float DEFAULT '0',
  `recargo_equivalencia` float DEFAULT '0',
  `base1` double DEFAULT '0',
  `base2` double DEFAULT '0',
  `base3` double DEFAULT '0' COMMENT '	',
  `base4` double DEFAULT '0',
  `porc_iva1` float DEFAULT '0',
  `porc_iva2` float DEFAULT '0',
  `porc_iva3` float DEFAULT '0',
  `porc_iva4` float DEFAULT '0',
  `iva1` double DEFAULT '0',
  `iva2` double DEFAULT '0',
  `iva3` double DEFAULT '0',
  `iva4` double DEFAULT '0',
  `porc_rec1` float DEFAULT '0',
  `porc_rec2` float DEFAULT '0',
  `porc_rec3` float DEFAULT '0',
  `porc_rec4` float DEFAULT '0',
  `rec1` double DEFAULT '0',
  `rec2` double DEFAULT '0',
  `rec3` double DEFAULT '0',
  `rec4` double DEFAULT '0',
  `total1` double DEFAULT '0',
  `total2` double DEFAULT '0',
  `total3` double DEFAULT '0',
  `total4` double DEFAULT '0',
  `total_base` double DEFAULT '0',
  `total_iva` double DEFAULT '0',
  `total_retencion` double DEFAULT '0',
  `total_recargo` double DEFAULT '0',
  `total` double DEFAULT '0',
  `id_forma_pago` int(11) DEFAULT '0',
  `forma_pago` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `importe_pagado_total` double DEFAULT '0',
  `id_tipo_gasto` int(11) DEFAULT '0',
  `comentario` text COLLATE utf8_unicode_ci,
  `pagado` tinyint(1) DEFAULT '0',
  `importe_deuda_pendiente` double DEFAULT '0',
  `albaran` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto1` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto2` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto3` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `imp_gasto1` double DEFAULT NULL,
  `imp_gasto2` double DEFAULT NULL,
  `imp_gasto3` double DEFAULT NULL,
  `gasto_to_coste` tinyint(1) DEFAULT NULL,
  `porc_iva_gasto1` float DEFAULT '0',
  `porc_iva_gasto2` float DEFAULT '0',
  `porc_iva_gasto3` float DEFAULT '0',
  `iva_gasto1` float DEFAULT '0',
  `iva_gasto2` float DEFAULT '0',
  `iva_gasto3` float DEFAULT '0',
  `total_dto` double DEFAULT NULL,
  `ejercicio` int(5) DEFAULT NULL,
  `contabilizada` tinyint(1) DEFAULT '0',
  `subtotal` double DEFAULT NULL,
  `codigo_proveedor` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `impreso` tinyint(1) DEFAULT '0',
  `editable` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `id_tipo_gasto` (`id_tipo_gasto`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`histovales` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_vale` int(11) DEFAULT '0',
  `fecha` date DEFAULT NULL,
  `vencimiento_vale` date DEFAULT NULL,
  `id_usuario` int(11) DEFAULT NULL,
  `importe` decimal(9,2) DEFAULT '0.00',
  `id_ticket` int(11) DEFAULT '0',
  `id_cliente` int(11) DEFAULT '0',
  `cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`lin_alb` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cab` int(11) DEFAULT NULL,
  `id_articulo` int(11) DEFAULT NULL,
  `codigo` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cantidad` float DEFAULT '0',
  `descripcion` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `precio` double DEFAULT '0',
  `precio_recom` double NOT NULL DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `dto` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `porc_iva` float DEFAULT '0',
  `iva` double DEFAULT '0',
  `porc_rec` float DEFAULT '0',
  `rec` double DEFAULT '0',
  `total` double DEFAULT '0',
  `promocion` tinyint(1) DEFAULT '0',
  `id_lote` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`lin_alb_pro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cab` int(11) DEFAULT NULL,
  `id_articulo` int(11) DEFAULT NULL,
  `codigo` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `descripcion` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `precio` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `porc_iva` float DEFAULT '0',
  `porc_rec` float DEFAULT '0',
  `rec` double DEFAULT '0',
  `cantidad` int(11) DEFAULT '0',
  `total` double DEFAULT '0',
  `dto` double DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `iva` double DEFAULT '0',
  `codigo_articulo_proveedor` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `coste_real` double DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`lin_fac` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cab` int(11) DEFAULT NULL,
  `id_articulo` int(11) DEFAULT NULL,
  `codigo` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cantidad` float DEFAULT '0',
  `descripcion` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `precio` double DEFAULT '0',
  `precio_recom` double NOT NULL DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `dto` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `porc_iva` float DEFAULT '0',
  `iva` double DEFAULT '0',
  `porc_rec` float DEFAULT '0',
  `rec` double DEFAULT '0',
  `total` double DEFAULT '0',
  `promocion` tinyint(1) DEFAULT '0',
  `id_lote` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`lin_fac_pro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cab` int(11) DEFAULT NULL,
  `id_articulo` int(11) DEFAULT NULL,
  `codigo` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `codigo_articulo_proveedor` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cantidad` float DEFAULT '0',
  `descripcion` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `precio` double DEFAULT '0',
  `subtotal` double DEFAULT NULL,
  `dto` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `porc_iva` float DEFAULT '0',
  `total` double DEFAULT '0',
  `iva` double DEFAULT '0',
  `pedido` int(11) DEFAULT '0',
  `porc_rec` float DEFAULT '0',
  `rec` double DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `cCodigo` (`codigo`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`lin_ped` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cab` int(11) DEFAULT NULL,
  `id_articulo` int(11) DEFAULT NULL,
  `codigo` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cantidad` float DEFAULT '0',
  `descripcion` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `precio` double DEFAULT '0',
  `precio_recom` double NOT NULL DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `dto` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `porc_iva` float DEFAULT '0',
  `iva` double DEFAULT '0',
  `porc_rec` float DEFAULT '0',
  `rec` double DEFAULT '0',
  `total` double DEFAULT '0',
  `cantidad_a_servir` float DEFAULT '0',
  `id_lote` int(11) DEFAULT NULL,
  `promocion` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`lin_ped_pro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cab` int(11) DEFAULT NULL,
  `id_articulo` int(11) DEFAULT '0',
  `codigo` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `descripcion` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cantidad` int(11) DEFAULT '0',
  `precio` double DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `dto` double DEFAULT '0',
  `porc_iva` float DEFAULT '0',
  `iva` double DEFAULT '0',
  `porc_rec` float DEFAULT '0',
  `rec` double DEFAULT '0',
  `total` double DEFAULT '0',
  `cantidad_recibida` int(11) DEFAULT '0',
  `etiquetas` int(11) DEFAULT '0',
  `cantidad_pendiente` int(11) DEFAULT '0',
  `cerrado` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`lin_pre` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cab` int(11) DEFAULT NULL,
  `id_articulo` int(11) DEFAULT NULL,
  `codigo` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cantidad` float DEFAULT '0',
  `descripcion` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `precio` double DEFAULT '0',
  `precio_recom` double NOT NULL DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `dto` double DEFAULT '0',
  `porc_iva` float DEFAULT '0',
  `iva` double DEFAULT '0',
  `porc_rec` float DEFAULT '0',
  `rec` double DEFAULT '0',
  `total` double DEFAULT '0',
  `promocion` tinyint(1) DEFAULT '0',
  `id_lote` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`lin_res` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cab` int(11) DEFAULT NULL,
  `id_articulo` int(11) DEFAULT NULL,
  `codigo` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `descripcion` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cantidad` int(11) DEFAULT '0',
  `precio` double DEFAULT '0',
  `precio_recom` double NOT NULL DEFAULT '0',
  `total` double DEFAULT '0',
  `fecha_reserva` date DEFAULT NULL,
  `reservado_hasta` date DEFAULT NULL,
  `importe_dto` double DEFAULT '0',
  `promocion` tinyint(1) DEFAULT '0',
  `id_lote` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`lin_tpv` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cab` int(11) DEFAULT NULL,
  `id_articulo` int(11) DEFAULT '0',
  `codigo` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `descripcion` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `precio` double DEFAULT '0',
  `cantidad` float DEFAULT '0',
  `importe` double DEFAULT '0',
  `porc_iva` float DEFAULT '0',
  `iva` double DEFAULT '0',
  `porc_rec` float DEFAULT '0',
  `rec` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `total` double DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `fecha_linea` date DEFAULT NULL,
  `promocion` tinyint(1) DEFAULT '0',
  `dev_act` float NOT NULL DEFAULT '0',
  `devolucion` float NOT NULL DEFAULT '0',
  `id_lote` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `id_Articulo` (`id_articulo`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`lin_tpv_2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cab` int(11) DEFAULT NULL,
  `descripcion` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tipo` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `valor` double DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`moneda_caja` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_moneda` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `valor_moneda` double DEFAULT NULL,
  `id_moneda_base` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `orden` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`ped_cli` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `albaran` int(11) DEFAULT '0',
  `pedido` int(11) DEFAULT '0',
  `id_divisa` int(11) NOT NULL DEFAULT '1',
  `fecha` date DEFAULT NULL,
  `pedido_cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_cliente` int(11) DEFAULT '0',
  `codigo_cliente` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais` int(11) DEFAULT NULL,
  `cif` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `telefono` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `movil` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `recargo_equivalencia` tinyint(1) DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `porc_dto` float DEFAULT '0',
  `porc_dto_pp` double DEFAULT '0',
  `dto_pp` double DEFAULT '0',
  `dto` double DEFAULT '0',
  `base1` double DEFAULT '0',
  `base2` double DEFAULT '0',
  `base3` double DEFAULT '0',
  `base4` double DEFAULT '0',
  `porc_iva1` float DEFAULT '0',
  `porc_iva2` float DEFAULT '0',
  `porc_iva3` float DEFAULT '0',
  `porc_iva4` float DEFAULT '0',
  `iva1` double DEFAULT '0',
  `iva2` double DEFAULT '0',
  `iva3` double DEFAULT '0',
  `iva4` double DEFAULT '0',
  `porc_rec1` float DEFAULT '0',
  `porc_rec2` float DEFAULT '0',
  `porc_rec3` float DEFAULT '0',
  `porc_rec4` float DEFAULT '0',
  `rec1` double DEFAULT '0',
  `rec2` double DEFAULT '0',
  `rec3` double DEFAULT '0',
  `rec4` double DEFAULT '0',
  `total1` double DEFAULT '0',
  `total2` double DEFAULT '0',
  `total3` double DEFAULT '0',
  `total4` double DEFAULT '0',
  `base_total` double DEFAULT '0',
  `iva_total` double DEFAULT '0',
  `rec_total` double DEFAULT '0',
  `total_albaran` double DEFAULT '0',
  `impreso` tinyint(1) DEFAULT '0',
  `facturado` tinyint(1) DEFAULT '0',
  `factura` varchar(45) COLLATE utf8_unicode_ci DEFAULT '0',
  `fecha_factura` date DEFAULT NULL,
  `comentario` text COLLATE utf8_unicode_ci,
  `entregado_a_cuenta` double DEFAULT '0',
  `traspasado_albaran` tinyint(1) DEFAULT '0',
  `traspasado_factura` tinyint(1) DEFAULT '0',
  `direccion_entrega1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion_entrega2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp_entrega` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais_entrega` int(11) DEFAULT NULL,
  `email_entrega` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `comentarios_entrega` text COLLATE utf8_unicode_ci,
  `enviado` tinyint(1) DEFAULT '0',
  `completo` tinyint(1) DEFAULT '0',
  `entregado` tinyint(1) DEFAULT '0',
  `fecha_limite_entrega` date DEFAULT NULL,
  `id_forma_pago` int(11) DEFAULT '0',
  `total_pedido` double DEFAULT NULL,
  `desc_gasto1` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto2` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto3` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `imp_gasto1` double DEFAULT NULL,
  `imp_gasto2` double DEFAULT NULL,
  `imp_gasto3` double DEFAULT NULL,
  `gasto_to_coste` tinyint(1) DEFAULT NULL,
  `porc_iva_gasto1` float DEFAULT '0',
  `porc_iva_gasto2` float DEFAULT '0',
  `porc_iva_gasto3` float DEFAULT '0',
  `iva_gasto1` float DEFAULT '0',
  `iva_gasto2` float DEFAULT '0',
  `iva_gasto3` float DEFAULT '0',
  `ejercicio` int(5) DEFAULT NULL,
  `editable` tinyint(1) DEFAULT '1',
  `id_transportista` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`ped_pro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pedido` int(11) DEFAULT '0',
  `ejercicio` int(11) DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `recepcion` date DEFAULT NULL,
  `id_proveedor` int(11) DEFAULT '0',
  `codigo_proveedor` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `proveedor` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais` int(11) DEFAULT NULL,
  `cif_nif` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `base_total` double DEFAULT '0',
  `subtotal` double DEFAULT '0',
  `dto` double DEFAULT '0',
  `rec_total` double DEFAULT '0',
  `total` double DEFAULT '0',
  `enviado` tinyint(1) DEFAULT '0',
  `recibido` tinyint(1) DEFAULT '0',
  `recibido_completo` tinyint(1) DEFAULT '0',
  `genero_pendiente` tinyint(1) DEFAULT '0',
  `traspasado` tinyint(1) DEFAULT '0',
  `pedido_cliente` int(11) DEFAULT '0',
  `id_forma_pago` int(11) DEFAULT '0',
  `comentario` text COLLATE utf8_unicode_ci,
  `fecha_entrega` date DEFAULT NULL,
  `direccion_entrega1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion_entrega2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp_entrega` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion_entrega` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia_entrega` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais_entrega` int(11) DEFAULT NULL,
  `nombre_cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `horario_activo` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `telefono` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `movil` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `base1` double DEFAULT NULL,
  `base2` double DEFAULT NULL,
  `base3` double DEFAULT NULL,
  `base4` double DEFAULT NULL,
  `porc_iva1` int(11) DEFAULT NULL,
  `porc_iva2` int(11) DEFAULT NULL,
  `porc_iva3` int(11) DEFAULT NULL,
  `porc_iva4` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iva1` double DEFAULT NULL,
  `iva2` double DEFAULT NULL,
  `iva3` double DEFAULT NULL,
  `iva4` double DEFAULT NULL,
  `porc_rec1` float DEFAULT NULL,
  `porc_rec2` float DEFAULT NULL,
  `porc_rec3` float DEFAULT NULL,
  `porc_rec4` float DEFAULT NULL,
  `rec1` double DEFAULT NULL,
  `rec2` double DEFAULT NULL,
  `rec3` double DEFAULT NULL,
  `rec4` double DEFAULT NULL,
  `total1` double DEFAULT NULL,
  `total2` double DEFAULT NULL,
  `total3` double DEFAULT NULL,
  `total4` double DEFAULT NULL,
  `impreso` tinyint(1) DEFAULT NULL,
  `desc_gasto1` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto2` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `desc_gasto3` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `imp_gasto1` double DEFAULT NULL,
  `imp_gasto2` double DEFAULT NULL,
  `imp_gasto3` double DEFAULT NULL,
  `gasto_to_coste` tinyint(1) DEFAULT NULL,
  `porc_iva_gasto1` float DEFAULT '0',
  `porc_iva_gasto2` float DEFAULT '0',
  `porc_iva_gasto3` float DEFAULT '0',
  `iva_gasto1` float DEFAULT '0',
  `iva_gasto2` float DEFAULT '0',
  `iva_gasto3` float DEFAULT '0',
  `recargo_equivalencia` tinyint(1) DEFAULT NULL,
  `editable` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`recibos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fecha` date DEFAULT NULL,
  `fecha_cobro` date DEFAULT NULL,
  `descripcion_fecha1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `descripcion_fecha2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `localidad` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `recibo` int(11) DEFAULT '0',
  `id_cliente` int(11) DEFAULT '0',
  `cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais` int(11) DEFAULT NULL,
  `concepto` text COLLATE utf8_unicode_ci,
  `importe` double DEFAULT '0',
  `importe_en_texto` text COLLATE utf8_unicode_ci,
  `descripcion_entidad` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `descripcion_oficina` varchar(254) COLLATE utf8_unicode_ci DEFAULT NULL,
  `entidad` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `oficina_entidad` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dc_cuenta` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cuenta_corriente` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cobrado` tinyint(1) DEFAULT '0',
  `ejercicio` int(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`report` (
  `report_id` int(11) NOT NULL AUTO_INCREMENT,
  `report_name` text NOT NULL,
  `report_descrip` text,
  `report_source` text NOT NULL,
  `report_grade` int(11) NOT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
CREATE TABLE `@empresa@`.`reservas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `reserva` int(11) DEFAULT '0',
  `fecha` date DEFAULT NULL,
  `id_cliente` int(11) DEFAULT '0',
  `cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direccion1` varchar(100) CHARACTER SET ucs2 DEFAULT NULL,
  `direccion2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cp` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `poblacion` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `provincia` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_pais` int(11) DEFAULT NULL,
  `telefono1` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `telefono2` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fecha_limite` date DEFAULT NULL,
  `importe` double DEFAULT '0',
  `pendiente` double DEFAULT '0',
  `entregado` double DEFAULT '0',
  `ejercicio` int(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`seguimiento` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `usuario` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fecha` datetime DEFAULT NULL,
  `accion` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `comentarios` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`series` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `serie` char(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `comentarios` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `@empresa@`.`vales` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `numero` int(11) DEFAULT '0',
  `codigo` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `fecha_vencimiento_vale` date DEFAULT NULL,
  `id_usuario` int(11) DEFAULT NULL,
  `importe` double DEFAULT '0',
  `id_ticket` int(11) DEFAULT '0',
  `id_cliente` int(11) DEFAULT '0',
  `cliente` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `agotado` tinyint(1) DEFAULT '0',
  `ejercicio` int(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `@empresa@`.`series` (`serie`) VALUES ('A');
