CREATE TABLE IF NOT EXISTS `agenda` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `dFecha` date DEFAULT NULL,
  `cHora` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_Usuario` int(11) DEFAULT '0',
  `cInicio` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cFin` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cAsunto` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcionAsunto` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cEstado` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cAvisarTiempo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cImportancia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `alb_pro` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `cAlbaran` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFecha` date DEFAULT NULL,
  `id_Proveedor` int(11) DEFAULT '0',
  `cProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCifProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rTotal1` decimal(9,2) DEFAULT '0.00',
  `rTotal2` decimal(9,2) DEFAULT '0.00',
  `rTotal3` decimal(9,2) DEFAULT '0.00',
  `rTotal4` decimal(9,2) DEFAULT '0.00',
  `nIva1` decimal(9,2) DEFAULT '0.00',
  `nIva2` decimal(9,2) DEFAULT '0.00',
  `nIva3` decimal(9,2) DEFAULT '0.00',
  `nIva4` decimal(9,2) DEFAULT '0.00',
  `rIva1` decimal(9,2) DEFAULT '0.00',
  `rIva2` decimal(9,2) DEFAULT '0.00',
  `rIva3` decimal(9,2) DEFAULT '0.00',
  `rIva4` decimal(9,2) DEFAULT '0.00',
  `rBase1` decimal(9,2) DEFAULT '0.00',
  `rBase2` decimal(9,2) DEFAULT '0.00',
  `rBase3` decimal(9,2) DEFAULT '0.00',
  `rBase4` decimal(9,2) DEFAULT '0.00',
  `cFactura` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rBaseTotal` decimal(9,2) DEFAULT '0.00',
  `rIvaTotal` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  `tComentario` text COLLATE utf8_unicode_ci,
  `nPedido` int(11) DEFAULT '0',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `articulos` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCodigoBarras` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCodigoFabricante` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcionReducida` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_Proveedor` int(11) DEFAULT '0',
  `id_Familia` int(11) DEFAULT '0',
  `cFamilia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_Seccion` int(11) DEFAULT '0',
  `cSeccion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_Subfamilia` int(11) DEFAULT '0',
  `cSubfamilia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nTipoIva` decimal(9,2) DEFAULT '0.00',
  `rCoste` decimal(9,2) DEFAULT '0.00',
  `rTarifa1` decimal(9,2) DEFAULT '0.00',
  `rTarifa2` decimal(9,2) DEFAULT '0.00',
  `rTarifa3` decimal(9,2) DEFAULT '0.00',
  `rDto` decimal(9,2) DEFAULT '0.00',
  `nDtoProveedor` decimal(9,2) DEFAULT '0.00',
  `nDtoproveedor2` decimal(9,2) DEFAULT '0.00',
  `nDtoProveedor3` decimal(9,2) DEFAULT '0.00',
  `dUltimaCompra` date DEFAULT NULL,
  `dUltimaVenta` date DEFAULT NULL,
  `nMargen1` decimal(9,2) DEFAULT '0.00',
  `nMargen2` decimal(9,2) DEFAULT '0.00',
  `nMargen3` decimal(9,2) DEFAULT '0.00',
  `rPrecioMedio` decimal(9,2) DEFAULT '0.00',
  `rPrecioMedio2` decimal(9,2) DEFAULT '0.00',
  `rPrecioMedio3` decimal(9,2) DEFAULT '0.00',
  `nUnidadesCompradas` int(11) DEFAULT '0',
  `nUnidadesVendidas` int(11) DEFAULT '0',
  `rAcumuladoCompras` decimal(9,2) DEFAULT '0.00',
  `rAcumuladoVentas` decimal(9,2) DEFAULT '0.00',
  `bImagen` blob,
  `tComentario` text COLLATE utf8_unicode_ci,
  `nStockMaximo` int(11) DEFAULT '0',
  `nStockMinimo` int(11) DEFAULT '0',
  `nStockReal` int(11) DEFAULT '0',
  `cTipoUnidad` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lControlarStock` int(11) DEFAULT '0',
  `cModelo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTalla` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cColor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cComposicion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lPvpIncluyeIva` int(11) DEFAULT '0',
  `dFechaPrevistaRecepcion` date DEFAULT NULL,
  `nCantidadPendienteRecibir` int(11) DEFAULT '0',
  `nReservados` int(11) DEFAULT '0',
  `lMostrarWeb` int(11) DEFAULT '0',
  `nEtiquetas` int(11) DEFAULT '0',
  `nPaquetes` int(11) DEFAULT '0',
  `cLocalizacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=4 ;

CREATE TABLE IF NOT EXISTS `bancos` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `cDescripcion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cEntidad` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cOficina` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDc` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCuenta` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rSaldo` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `cab_alb` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `nAlbaran` int(11) DEFAULT '0',
  `dFecha` date DEFAULT NULL,
  `cPedidoCli` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_Cliente` int(11) DEFAULT '0',
  `cCodigoCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvincia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCP` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPais` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCif` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lRecargoEquivalencia` int(11) DEFAULT '0',
  `rSubtotal` decimal(9,2) DEFAULT '0.00',
  `rDto` decimal(9,2) DEFAULT '0.00',
  `nDto` decimal(9,2) DEFAULT '0.00',
  `rBase1` decimal(9,2) DEFAULT '0.00',
  `rBase2` decimal(9,2) DEFAULT '0.00',
  `rBase3` decimal(9,2) DEFAULT '0.00',
  `rBase4` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva1` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva2` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva3` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva4` decimal(9,2) DEFAULT '0.00',
  `rImporteIva1` decimal(9,2) DEFAULT '0.00',
  `rImporteIva2` decimal(9,2) DEFAULT '0.00',
  `rImporteIva3` decimal(9,2) DEFAULT '0.00',
  `rImporteIva4` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRecargoEq1` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRecargoEq2` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRecargoEq3` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRecargoEq4` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq1` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq2` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq3` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq4` decimal(9,2) DEFAULT '0.00',
  `rTotal1` decimal(9,2) DEFAULT '0.00',
  `rTotal2` decimal(9,2) DEFAULT '0.00',
  `rTotal3` decimal(9,2) DEFAULT '0.00',
  `rTotal4` decimal(9,2) DEFAULT '0.00',
  `rBaseTotal` decimal(9,2) DEFAULT '0.00',
  `rIvaTotal` decimal(9,2) DEFAULT '0.00',
  `rRecargoEqTotal` decimal(9,2) DEFAULT '0.00',
  `rTotalAlbaran` decimal(9,2) DEFAULT '0.00',
  `lImpreso` int(11) DEFAULT '0',
  `lFacturado` int(11) DEFAULT '0',
  `cFactura` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFechaFactura` date DEFAULT NULL,
  `tComentario` text COLLATE utf8_unicode_ci,
  `rACuenta` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `cab_fac` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `cCodigoCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cFactura` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFecha` date DEFAULT NULL,
  `dFechaCobro` date DEFAULT NULL,
  `iId_Cliente` int(11) DEFAULT '0',
  `cCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCp` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvincia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPais` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCif` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lRecargoEquivalencia` int(11) DEFAULT '0',
  `rSubtotal` decimal(9,2) DEFAULT '0.00',
  `nDto` decimal(9,2) DEFAULT '0.00',
  `nDtoPP` decimal(9,2) DEFAULT '0.00',
  `rImporteDescuento` decimal(9,2) DEFAULT '0.00',
  `rImporteDescuentoPP` decimal(9,2) DEFAULT '0.00',
  `rBase` decimal(9,2) DEFAULT '0.00',
  `nIRPF` decimal(7,2) DEFAULT '0.00',
  `rImporteIRPF` decimal(9,2) DEFAULT '0.00',
  `nIva` decimal(9,2) DEFAULT '0.00',
  `rImporteIva` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  `lImpresa` int(11) DEFAULT '0',
  `lCobrada` int(11) DEFAULT '0',
  `lContabilizada` int(11) DEFAULT '0',
  `id_FormaPago` int(11) DEFAULT '0',
  `cFormaPago` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tComentario` text COLLATE utf8_unicode_ci,
  `rBase1` decimal(9,2) DEFAULT '0.00',
  `rBase2` decimal(9,2) DEFAULT '0.00',
  `rBase3` decimal(9,2) DEFAULT '0.00',
  `rBase4` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIVA1` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIVA2` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIVA3` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIVA4` decimal(9,2) DEFAULT '0.00',
  `rIVA1` decimal(9,2) DEFAULT '0.00',
  `rIVA2` decimal(9,2) DEFAULT '0.00',
  `rIVA3` decimal(9,2) DEFAULT '0.00',
  `rIVA4` decimal(9,2) DEFAULT '0.00',
  `rTotal1` decimal(9,2) DEFAULT '0.00',
  `rTotal2` decimal(9,2) DEFAULT '0.00',
  `rTotal3` decimal(9,2) DEFAULT '0.00',
  `rTotal4` decimal(9,2) DEFAULT '0.00',
  `nRec1` decimal(9,2) DEFAULT '0.00',
  `nRec2` decimal(9,2) DEFAULT '0.00',
  `nRec3` decimal(9,2) DEFAULT '0.00',
  `nRec4` decimal(9,2) DEFAULT '0.00',
  `rRecargoEq1` decimal(9,2) DEFAULT '0.00',
  `rRecargoEq2` decimal(9,2) DEFAULT '0.00',
  `rRecargoEq3` decimal(9,2) DEFAULT '0.00',
  `rRecargoEq4` decimal(9,2) DEFAULT '0.00',
  `rTotalRecargoEq` decimal(9,2) DEFAULT '0.00',
  `rEntregadoaCuenta` decimal(9,2) DEFAULT '0.00',
  `rImportePendiente` decimal(9,2) DEFAULT '0.00',
  `cCodigoEntidad` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cOficinaEntidad` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDCCuenta` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cNumeroCuenta` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPedidoCliente` int(11) DEFAULT '0',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=5 ;

CREATE TABLE IF NOT EXISTS `cab_pre` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `nPresupuesto` int(11) DEFAULT '0',
  `dFecha` date DEFAULT NULL,
  `dValidoHasta` date DEFAULT NULL,
  `id_Cliente` int(11) DEFAULT '0',
  `cCodigoCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCif` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCP` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvincia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPais` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTelefono` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cMovil` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cFax` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nDto` decimal(9,2) DEFAULT '0.00',
  `tComentarios` text COLLATE utf8_unicode_ci,
  `rImporte` decimal(9,2) DEFAULT '0.00',
  `rSubtotal` decimal(9,2) DEFAULT '0.00',
  `rDescuento` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  `lImpreso` int(11) DEFAULT '0',
  `lAprobado` int(11) DEFAULT '0',
  `dFechaAprobacion` date DEFAULT NULL,
  `rImporteFactura` decimal(9,2) DEFAULT '0.00',
  `rImportePendiente` decimal(9,2) DEFAULT '0.00',
  `cFactura` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nAlbaran` int(11) DEFAULT '0',
  `nPedido` int(11) DEFAULT '0',
  `id_FormaPago` int(11) DEFAULT '0',
  `cCodigoFormaPago` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcionFormaPago` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tLugarEntrega` text COLLATE utf8_unicode_ci,
  `cAtencionde` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rBase1` decimal(9,2) DEFAULT '0.00',
  `rBase2` decimal(9,2) DEFAULT '0.00',
  `rBase3` decimal(9,2) DEFAULT '0.00',
  `rBase4` decimal(9,2) DEFAULT '0.00',
  `nIva1` decimal(9,2) DEFAULT '0.00',
  `nIva2` decimal(9,2) DEFAULT '0.00',
  `nIva3` decimal(9,2) DEFAULT '0.00',
  `nIva4` decimal(9,2) DEFAULT '0.00',
  `rIva1` decimal(9,2) DEFAULT '0.00',
  `rIva2` decimal(9,2) DEFAULT '0.00',
  `rIva3` decimal(9,2) DEFAULT '0.00',
  `rIva4` decimal(9,2) DEFAULT '0.00',
  `nRecargoEquivalencia1` decimal(9,2) DEFAULT '0.00',
  `nRecargoEquivalencia2` decimal(9,2) DEFAULT '0.00',
  `nRecargoEquivalencia3` decimal(9,2) DEFAULT '0.00',
  `nRecargoEquivalencia4` decimal(9,2) DEFAULT '0.00',
  `rRec1` decimal(9,2) DEFAULT '0.00',
  `rRec2` decimal(9,2) DEFAULT '0.00',
  `rRec3` decimal(9,2) DEFAULT '0.00',
  `rRec4` decimal(9,2) DEFAULT '0.00',
  `rTotal1` decimal(9,2) DEFAULT '0.00',
  `rTotal2` decimal(9,2) DEFAULT '0.00',
  `rTotal3` decimal(9,2) DEFAULT '0.00',
  `rTotal4` decimal(9,2) DEFAULT '0.00',
  `lRecargoEquivalencia` int(11) DEFAULT '0',
  `cEmail` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rTotalIva` decimal(9,2) DEFAULT '0.00',
  `rTotalRec` decimal(9,2) DEFAULT '0.00',
  `rImporte1` decimal(9,2) DEFAULT NULL,
  `rImporte2` decimal(9,2) DEFAULT NULL,
  `rImporte3` decimal(9,2) DEFAULT NULL,
  `rImporte4` decimal(9,2) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=8 ;

CREATE TABLE IF NOT EXISTS `cab_tpv` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `nCaja` int(11) DEFAULT '0',
  `nTicket` int(11) DEFAULT '0',
  `dFecha` date DEFAULT NULL,
  `cHora` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cUsuario` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cNombreUsuario` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_Cliente` int(11) DEFAULT '0',
  `cCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cNombreCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lticketEnEpera` int(11) DEFAULT '0',
  `lPendienteCobro` int(11) DEFAULT '0',
  `cFormaPago` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTipoTarjeta` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lImpreso` int(11) DEFAULT '0',
  `rImporte` decimal(9,2) DEFAULT '0.00',
  `rBase1` decimal(9,2) DEFAULT '0.00',
  `rBase2` decimal(9,2) DEFAULT '0.00',
  `rBase3` decimal(9,2) DEFAULT '0.00',
  `rBase4` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva1` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva2` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva3` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva4` decimal(9,2) DEFAULT '0.00',
  `rImporteIva1` decimal(9,2) DEFAULT '0.00',
  `rImporteIva2` decimal(9,2) DEFAULT '0.00',
  `rImporteIva3` decimal(9,2) DEFAULT '0.00',
  `rImporteIva4` decimal(9,2) DEFAULT '0.00',
  `rTotal1` decimal(9,2) DEFAULT '0.00',
  `rTotal2` decimal(9,2) DEFAULT '0.00',
  `rTotal3` decimal(9,2) DEFAULT '0.00',
  `rTotal4` decimal(9,2) DEFAULT '0.00',
  `rSubotal` decimal(9,2) DEFAULT '0.00',
  `rDto` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRe1` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRe2` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRe3` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRe4` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq1` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq2` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq3` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq4` decimal(9,2) DEFAULT '0.00',
  `rTotalRecargoEq` decimal(9,2) DEFAULT '0.00',
  `rImporteTotalIva` decimal(9,2) DEFAULT '0.00',
  `rCobrado` decimal(9,2) DEFAULT '0.00',
  `rPendienteCobro` decimal(9,2) DEFAULT '0.00',
  `rImporteEfectivo` decimal(9,2) DEFAULT '0.00',
  `rImporteTarjeta` decimal(9,2) DEFAULT '0.00',
  `rImporteCheque` decimal(9,2) DEFAULT '0.00',
  `rImporteCredito` decimal(9,2) DEFAULT '0.00',
  `rImporteDtoRedondeo` decimal(9,2) DEFAULT '0.00',
  `rImporteCambio` decimal(9,2) DEFAULT '0.00',
  `rEntregado` decimal(9,2) DEFAULT '0.00',
  `lPasadoAlbaranFactura` int(11) DEFAULT '0',
  `nNumeroAlbaran` int(11) DEFAULT '0',
  `nNumeroFactura` int(11) DEFAULT '0',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `cajaabierta` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dFechaAbertura` date DEFAULT NULL,
  `cHoraAbertura` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nCaja` int(11) DEFAULT '0',
  `id_UsuarioAbertura` int(11) DEFAULT '0',
  `cUsuarioAbertura` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_UsuarioCierre` int(11) DEFAULT '0',
  `cUsuarioCierre` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rImporteAbertura` decimal(9,2) DEFAULT '0.00',
  `rImporteCierreAnterior` decimal(9,2) DEFAULT '0.00',
  `lCajaCerrada` int(11) DEFAULT '0',
  `rMoneda` decimal(9,2) DEFAULT '0.00',
  `rCheque` decimal(9,2) DEFAULT '0.00',
  `rTarjeta` decimal(9,2) DEFAULT '0.00',
  `rCredito` decimal(9,2) DEFAULT '0.00',
  `rEntradasExtras` decimal(9,2) DEFAULT '0.00',
  `rSalidasExtras` decimal(9,2) DEFAULT '0.00',
  `rImportePendiente` decimal(9,2) DEFAULT '0.00',
  `rVales` decimal(9,2) DEFAULT '0.00',
  `rImporteCierre` decimal(9,2) DEFAULT '0.00',
  `rValorRealCaja` decimal(9,2) DEFAULT '0.00',
  `rDescuadre` decimal(9,2) DEFAULT '0.00',
  `rImporteACuenta` decimal(9,2) DEFAULT '0.00',
  `rImporteCambios` decimal(9,2) DEFAULT '0.00',
  `rValesEmitidos` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `cierrecaja` (
  `id` int(11) NOT NULL,
  `dFechaCierre` date DEFAULT NULL,
  `rDeudas` decimal(9,2) DEFAULT '0.00',
  `rEntregasACuenta` decimal(9,2) DEFAULT '0.00',
  `rValesEmitidos` decimal(9,2) DEFAULT '0.00',
  `lCajaCerrada` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `clientes` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `cCodigoCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cApellido1` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cApellido2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cNombre` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cNombreFiscal` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cNombreComercial` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPersonaContacto` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCifNif` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion1` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCP` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvincia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPais` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTelefono1` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTelefono2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cFax` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cMovil` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cEmail` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cWeb` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccionFactura1` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccionFactura2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCPFactura` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacionFactura` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvinciaFactura` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPaisFactura` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccionAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccionAlmacen2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCPAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacionAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvinciaAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPaisAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFechaAlta` date DEFAULT NULL,
  `dFechaUltimaCompra` date DEFAULT NULL,
  `rAcumuladoVentas` decimal(9,2) DEFAULT '0.00',
  `rVentasEjercicio` decimal(9,2) DEFAULT '0.00',
  `rRiesgoMaximo` decimal(9,2) DEFAULT '0.00',
  `rDeudaActual` decimal(9,2) DEFAULT '0.00',
  `tComentarios` text COLLATE utf8_unicode_ci,
  `lBloqueado` int(11) DEFAULT '0',
  `tComentarioBloqueo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nPorcDtoCliente` decimal(9,2) DEFAULT '0.00',
  `lRecargoEquivalencia` int(11) DEFAULT '0',
  `cCuentaContable` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCuentaIvaRepercutido` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCuentaDeudas` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCuentaCobros` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cFormaPago` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nDiapago1` int(11) DEFAULT '0',
  `nDiaPago2` int(11) DEFAULT '0',
  `nTarifaCliente` int(11) DEFAULT '0',
  `rImporteACuenta` decimal(9,2) DEFAULT '0.00',
  `rVales` decimal(9,2) DEFAULT '0.00',
  `cCentidadBancaria` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cOficinaBancaria` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDC` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCuentaCorriente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFechaNacimiento` date DEFAULT NULL,
  `rImportePendiente` decimal(9,2) DEFAULT '0.00',
  `cTipoCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cAccesoWeb` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPasswordWeb` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nIRPF` int(11) DEFAULT '0',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=9 ;

CREATE TABLE IF NOT EXISTS `clientes_deuda` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Id_Cliente` int(11) DEFAULT '0',
  `dFecha` date DEFAULT NULL,
  `dVencimiento` date DEFAULT NULL,
  `cDocumento` int(11) DEFAULT '0',
  `Id_Ticket` int(11) DEFAULT '0',
  `Id_Factura` int(11) DEFAULT '0',
  `nTipo` int(11) DEFAULT '0',
  `rImporte` decimal(9,2) DEFAULT '0.00',
  `rPagado` decimal(9,2) DEFAULT '0.00',
  `rPendienteCobro` decimal(9,2) DEFAULT '0.00',
  `cEntidad` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cOficina` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDC` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCuenta` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `clientes_entregas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Id_Cliente` int(11) DEFAULT '0',
  `dFecha` date DEFAULT NULL,
  `rImporte` decimal(9,2) DEFAULT '0.00',
  `nDocumento` int(11) DEFAULT '0',
  `cTipo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `conceptostallas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cConcepto` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `dependient` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cNombre` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCP` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvincia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFechaNacimiento` date DEFAULT NULL,
  `cTelefono1` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTelefono2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cMovil` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cNombrePariente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPassword` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rCosteHora` decimal(9,2) DEFAULT '0.00',
  `rCosteHoraExtra` decimal(9,2) DEFAULT '0.00',
  `dFechaAlta` date DEFAULT NULL,
  `dFinContrato` date DEFAULT NULL,
  `cCategoria` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `devoluciones` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nTicket` int(11) DEFAULT '0',
  `dFechaDevolucion` date DEFAULT NULL,
  `cAtendidoPor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_Cliente` int(11) DEFAULT '0',
  `cCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tComentarios` text COLLATE utf8_unicode_ci,
  `cCodArticulo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescArticulo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `fac_pro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cFactura` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFecha` date DEFAULT NULL,
  `dRecepcion` date DEFAULT NULL,
  `cPedido` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Id_Proveedor` int(11) DEFAULT '0',
  `cProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCifProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lRetencionIRPF` int(11) DEFAULT '0',
  `lRecargoEquivalencia` int(11) DEFAULT '0',
  `rBase1` decimal(9,2) DEFAULT '0.00',
  `rBase2` decimal(9,2) DEFAULT '0.00',
  `rBase3` decimal(9,2) DEFAULT '0.00',
  `rBase4` decimal(9,2) DEFAULT '0.00',
  `nPorcIva1` decimal(9,2) DEFAULT '0.00',
  `nPorcIva2` decimal(9,2) DEFAULT '0.00',
  `nPorcIva3` decimal(9,2) DEFAULT '0.00',
  `nPorcIva4` decimal(9,2) DEFAULT '0.00',
  `rIVA1` decimal(9,2) DEFAULT '0.00',
  `rIVA2` decimal(9,2) DEFAULT '0.00',
  `rIVA3` decimal(9,2) DEFAULT '0.00',
  `rIVA4` decimal(9,2) DEFAULT '0.00',
  `nREC1` decimal(9,2) DEFAULT '0.00',
  `nREC2` decimal(9,2) DEFAULT '0.00',
  `nREC3` decimal(9,2) DEFAULT '0.00',
  `nREC4` decimal(9,2) DEFAULT '0.00',
  `rREC1` decimal(9,2) DEFAULT '0.00',
  `rREC2` decimal(9,2) DEFAULT '0.00',
  `rREC3` decimal(9,2) DEFAULT '0.00',
  `rREC4` decimal(9,2) DEFAULT '0.00',
  `rTotal1` decimal(9,2) DEFAULT '0.00',
  `rTotal2` decimal(9,2) DEFAULT '0.00',
  `rTotal3` decimal(9,2) DEFAULT '0.00',
  `rTotal4` decimal(9,2) DEFAULT '0.00',
  `rTotalBase` decimal(9,2) DEFAULT '0.00',
  `rTotalIVA` decimal(9,2) DEFAULT '0.00',
  `rTotalRetencion` decimal(9,2) DEFAULT '0.00',
  `rTotalRecargoEq` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  `cFormaPago` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nDiaPago1` decimal(10,0) DEFAULT NULL,
  `nDiaPago2` decimal(10,0) DEFAULT NULL,
  `nDiaPago3` decimal(10,0) DEFAULT NULL,
  `nDiaPago4` decimal(10,0) DEFAULT NULL,
  `rImportePagadoTotal` decimal(9,2) DEFAULT '0.00',
  `Id_TipoGasto` int(11) DEFAULT '0',
  `cTipoGasto` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tComentario` text COLLATE utf8_unicode_ci,
  `lPagado` int(11) DEFAULT '0',
  `rImporteDeudaPendiente` decimal(9,2) DEFAULT '0.00',
  `cCAlbaran` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `familias` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cFamilia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Id_Seccion` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `formpago` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cFormapago` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nDiaPago1` int(11) DEFAULT '0',
  `nDiaPago2` int(11) DEFAULT '0',
  `nDiaPago3` int(11) DEFAULT '0',
  `nDiaPago4` int(11) DEFAULT '0',
  `nDias1` int(11) DEFAULT '0',
  `nDias2` int(11) DEFAULT '0',
  `nDias3` int(11) DEFAULT '0',
  `nDias4` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `histoart` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Id_Articulo` int(11) DEFAULT '0',
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFecha` date DEFAULT NULL,
  `nCantidad` decimal(9,2) DEFAULT '0.00',
  `rImporte` decimal(9,2) DEFAULT '0.00',
  `cNombreUsuario` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `histovales` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nVale` int(11) DEFAULT '0',
  `dFecha` date DEFAULT NULL,
  `dVencimientoVale` date DEFAULT NULL,
  `cDependiente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rImporte` decimal(9,2) DEFAULT '0.00',
  `Id_Ticket` int(11) DEFAULT '0',
  `Id_Cliente` int(11) DEFAULT '0',
  `cCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `lin_alb` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Id_Cab` int(11) DEFAULT '0',
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nCantidad` decimal(9,2) DEFAULT '0.00',
  `cDescripcion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rPvp` decimal(9,2) DEFAULT '0.00',
  `rSubTotal` decimal(9,2) DEFAULT '0.00',
  `rDto` decimal(9,2) DEFAULT '0.00',
  `nDto` decimal(9,2) DEFAULT '0.00',
  `nPorcIva` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `lin_alb_pro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cab` int(11) DEFAULT '0',
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rCoste` decimal(9,2) DEFAULT '0.00',
  `nDto` decimal(9,2) DEFAULT '0.00',
  `rPvp1` decimal(9,2) DEFAULT '0.00',
  `rPvp2` decimal(9,2) DEFAULT '0.00',
  `rPvp3` decimal(9,2) DEFAULT '0.00',
  `nIva` decimal(9,2) DEFAULT '0.00',
  `nCantidad` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  `rDto` decimal(9,2) DEFAULT '0.00',
  `rSUBTOTAL` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `lin_fac` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_Cab` int(11) DEFAULT '0',
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nCantidad` decimal(9,2) DEFAULT '0.00',
  `cDescripcion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rPvp` decimal(9,2) DEFAULT '0.00',
  `nDto` decimal(9,2) DEFAULT '0.00',
  `rDto` decimal(9,2) DEFAULT '0.00',
  `rSubTotal` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  `nPorcIva` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=3 ;

CREATE TABLE IF NOT EXISTS `lin_fac_pro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Id_Cab` int(11) DEFAULT '0',
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nCantidad` decimal(9,2) DEFAULT '0.00',
  `rCosteBruto` decimal(9,2) DEFAULT '0.00',
  `nPorcDto` decimal(9,2) DEFAULT '0.00',
  `rDto` decimal(9,2) DEFAULT '0.00',
  `rCoste` decimal(9,2) DEFAULT '0.00',
  `nPorcIva` decimal(9,2) DEFAULT '0.00',
  `rIva` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  `nPedido` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `lin_ped` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Id_Cab` int(11) DEFAULT '0',
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nCantidad` decimal(9,2) DEFAULT '0.00',
  `cDescripcion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rPvp` decimal(9,2) DEFAULT '0.00',
  `rSubTotal` decimal(9,2) DEFAULT '0.00',
  `rDto` decimal(9,2) DEFAULT '0.00',
  `nDto` decimal(9,2) DEFAULT '0.00',
  `nPorcIva` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `lin_ped_pro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Id_Cab` int(11) DEFAULT '0',
  `Id_Articulo` int(11) DEFAULT '0',
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nCantidad` decimal(9,2) DEFAULT '0.00',
  `rCosteBruto` decimal(9,2) DEFAULT '0.00',
  `rSubtotal` decimal(9,2) DEFAULT '0.00',
  `nPorcDto` decimal(9,2) DEFAULT '0.00',
  `nDto` decimal(9,2) DEFAULT '0.00',
  `nPorcIva` decimal(9,2) DEFAULT '0.00',
  `rIVA` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  `rTarifa1` decimal(9,2) DEFAULT '0.00',
  `nMargen1` decimal(9,2) DEFAULT '0.00',
  `rTarifa2` decimal(9,2) DEFAULT '0.00',
  `nMargen2` decimal(9,2) DEFAULT '0.00',
  `rTarifa3` decimal(9,2) DEFAULT '0.00',
  `nMargen3` decimal(9,2) DEFAULT '0.00',
  `nCantidadRecibida` decimal(9,2) DEFAULT '0.00',
  `lRecibido` int(11) DEFAULT '0',
  `lTraspasado` int(11) DEFAULT '0',
  `cTalla` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cColor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCodigoInterno` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nEtiquetas` int(11) DEFAULT '0',
  `lOK` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `lin_pre` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Id_Cab` int(11) DEFAULT '0',
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nCantidad` decimal(9,2) DEFAULT '0.00',
  `rPvp` decimal(9,2) DEFAULT '0.00',
  `rSubTotal` decimal(9,2) DEFAULT '0.00',
  `nPorcDto` decimal(9,2) DEFAULT '0.00',
  `rDto` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  `nPorcIVA` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `lin_res` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Id_Cab` int(11) DEFAULT '0',
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nCantidad` int(11) DEFAULT '0',
  `rImporte` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  `Id_Cliente` int(11) DEFAULT '0',
  `cCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFechaReserva` date DEFAULT NULL,
  `dReservadoHasta` date DEFAULT NULL,
  `nDto` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `lin_tpv` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `id_Cab` int(11) DEFAULT '0',
  `id_Articulo` int(11) DEFAULT '0',
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rPvp` decimal(9,2) DEFAULT '0.00',
  `nCantidad` decimal(9,2) DEFAULT '0.00',
  `rImporte` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva` decimal(9,2) DEFAULT '0.00',
  `nPorcDto` decimal(9,2) DEFAULT '0.00',
  `nTotal` decimal(9,2) DEFAULT '0.00',
  `cTipo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rSubTotal` decimal(9,2) DEFAULT '0.00',
  `dFechaLinea` date DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `obligacionestrib` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cObligacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFecha` date DEFAULT NULL,
  `cModeloDocumento` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPeriodicidad` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ped_cli` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `nAlbaran` int(11) DEFAULT '0',
  `nPedido` int(11) DEFAULT '0',
  `dFecha` date DEFAULT NULL,
  `cPedido` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `id_Cliente` int(11) DEFAULT '0',
  `cCodigoCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvincia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCP` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPais` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCif` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lRecargoEquivalencia` int(11) DEFAULT '0',
  `rSubtotal` decimal(9,2) DEFAULT '0.00',
  `rDto` decimal(9,2) DEFAULT '0.00',
  `nDto` decimal(9,2) DEFAULT '0.00',
  `rBase1` decimal(9,2) DEFAULT '0.00',
  `rBase2` decimal(9,2) DEFAULT '0.00',
  `rBase3` decimal(9,2) DEFAULT '0.00',
  `rBase4` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva1` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva2` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva3` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeIva4` decimal(9,2) DEFAULT '0.00',
  `rImporteIva1` decimal(9,2) DEFAULT '0.00',
  `rImporteIva2` decimal(9,2) DEFAULT '0.00',
  `rImporteIva3` decimal(9,2) DEFAULT '0.00',
  `rImporteIva4` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRecargoEq1` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRecargoEq2` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRecargoEq3` decimal(9,2) DEFAULT '0.00',
  `nPorcentajeRecargoEq4` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq1` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq2` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq3` decimal(9,2) DEFAULT '0.00',
  `rImporteRecargoEq4` decimal(9,2) DEFAULT '0.00',
  `rTotal1` decimal(9,2) DEFAULT '0.00',
  `rTotal2` decimal(9,2) DEFAULT '0.00',
  `rTotal3` decimal(9,2) DEFAULT '0.00',
  `rTotal4` decimal(9,2) DEFAULT '0.00',
  `rBaseTotal` decimal(9,2) DEFAULT '0.00',
  `rIvaTotal` decimal(9,2) DEFAULT '0.00',
  `rRecargoEqTotal` decimal(9,2) DEFAULT '0.00',
  `rTotalAlbaran` decimal(9,2) DEFAULT '0.00',
  `lImpreso` int(11) DEFAULT '0',
  `lFacturado` int(11) DEFAULT '0',
  `cFactura` varchar(45) COLLATE utf8_unicode_ci DEFAULT '0',
  `dFechaFactura` date DEFAULT NULL,
  `tComentario` text COLLATE utf8_unicode_ci,
  `rACuenta` decimal(9,2) DEFAULT '0.00',
  `lTraspasadoAlb` int(11) DEFAULT '0',
  `lTraspasadoFac` int(11) DEFAULT '0',
  `cDireccionEntrega` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccionEntrega2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCPEntrega` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacionEntrega` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvinciaEntrega` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPaisEntrega` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lEnviado` int(11) DEFAULT '0',
  `lCompleto` int(11) DEFAULT '0',
  `lEntregado` int(11) DEFAULT '0',
  `dFechaLimiteEntrega` date DEFAULT NULL,
  `rTotalPedido` decimal(9,2) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `ped_pro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nPedido` int(11) DEFAULT '0',
  `cSerie` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFecha` date DEFAULT NULL,
  `dRecepcion` date DEFAULT NULL,
  `Id_Proveedor` int(11) DEFAULT '0',
  `cCodigoProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion1` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCP` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvincia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPais` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCifNif` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rBase` decimal(9,2) DEFAULT '0.00',
  `rSubotal` decimal(9,2) DEFAULT '0.00',
  `rDto` decimal(9,2) DEFAULT '0.00',
  `nIVA` decimal(9,2) DEFAULT '0.00',
  `rRecTotal` decimal(9,2) DEFAULT '0.00',
  `rTotal` decimal(9,2) DEFAULT '0.00',
  `lEnviado` int(11) DEFAULT '0',
  `lRecibido` int(11) DEFAULT '0',
  `lRecibidoCompleto` int(11) DEFAULT '0',
  `lGeneroPendiente` int(11) DEFAULT '0',
  `rBase1` decimal(9,2) DEFAULT '0.00',
  `rBase2` decimal(9,2) DEFAULT '0.00',
  `rBase3` decimal(9,2) DEFAULT '0.00',
  `rBase4` decimal(9,2) DEFAULT '0.00',
  `nPorcIva1` decimal(9,2) DEFAULT '0.00',
  `nPorcIva2` decimal(9,2) DEFAULT '0.00',
  `nPorcIva3` decimal(9,2) DEFAULT '0.00',
  `nPorcIva4` decimal(9,2) DEFAULT '0.00',
  `rIVA1` decimal(9,2) DEFAULT '0.00',
  `rIVA2` decimal(9,2) DEFAULT '0.00',
  `rIVA3` decimal(9,2) DEFAULT '0.00',
  `rIVA4` decimal(9,2) DEFAULT '0.00',
  `rTotal1` decimal(9,2) DEFAULT '0.00',
  `rTotal2` decimal(9,2) DEFAULT '0.00',
  `rTotal3` decimal(9,2) DEFAULT '0.00',
  `rTotal4` decimal(9,2) DEFAULT '0.00',
  `nMargenREC1` decimal(9,2) DEFAULT '0.00',
  `nMargenREC2` decimal(9,2) DEFAULT '0.00',
  `nMargenREC3` decimal(9,2) DEFAULT '0.00',
  `nMargenREC4` decimal(9,2) DEFAULT '0.00',
  `rREC1` decimal(9,2) DEFAULT '0.00',
  `rREC2` decimal(9,2) DEFAULT '0.00',
  `rREC3` decimal(9,2) DEFAULT '0.00',
  `rREC4` decimal(9,2) DEFAULT '0.00',
  `lTraspasado` int(11) DEFAULT '0',
  `nPedidoCliente` int(11) DEFAULT '0',
  `Id_FormaPago` int(11) DEFAULT '0',
  `cCodigoFormaPago` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cFormaPago` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dVencimiento1` date DEFAULT NULL,
  `dVencimiento2` date DEFAULT NULL,
  `dVencimiento3` date DEFAULT NULL,
  `dVencimiento4` date DEFAULT NULL,
  `lPagado1` int(11) DEFAULT '0',
  `lPagado2` int(11) DEFAULT '0',
  `lPagado3` int(11) DEFAULT '0',
  `lPagado4` int(11) DEFAULT '0',
  `tComentario` text COLLATE utf8_unicode_ci,
  `dFechaEntrega` date DEFAULT NULL,
  `cDireccion1Entrega` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion2Entrega` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCPEntrega` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacionEntrega` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvinciaEntrega` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPaisEntrega` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cNombreCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cHorarioActivo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `proveedores` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `cCodigo` int(11) DEFAULT '0',
  `cProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCif` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion1` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCP` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvincia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPais` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTelefono1` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTelefono2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTelefono3` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cFax` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cMovil` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cEMail` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cWeb` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPersonaContacto` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nDiaCobro` int(11) DEFAULT '0',
  `cDireccionAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCPAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacionAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvinciaAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPaisAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTelefonoAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cFaxAlmacen` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCodigoFormaPago` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFechaUltimaCompra` date DEFAULT NULL,
  `rAcumuladoCompras` decimal(9,2) DEFAULT '0.00',
  `cEntidadBancariaProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cOficinaBancariaProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDCProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCCProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cEntidadPagoProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cOficinaPagoProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDCPagoProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCuentaPagoProveedor` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCuentaIvaSoportado` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rRetencionIRPF` decimal(9,2) DEFAULT '0.00',
  `nTipoRetencion` int(11) DEFAULT '0',
  `cCuentaAplicacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCuentaPagos` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tComentarios` text COLLATE utf8_unicode_ci,
  `nDto` decimal(9,2) DEFAULT '0.00',
  `dFechaAlta` date DEFAULT NULL,
  `rDeudaMaxima` decimal(9,2) DEFAULT '0.00',
  `rDeudaActual` decimal(9,2) DEFAULT '0.00',
  `lRecargoEquivalencia` int(11) DEFAULT '0',
  `tTextoparaPedidos` text COLLATE utf8_unicode_ci,
  `rEntregadoaCuenta` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=5 ;

CREATE TABLE IF NOT EXISTS `recibos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dFecha` date DEFAULT NULL,
  `dFechaCobro` date DEFAULT NULL,
  `cDescripcionFecha1` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcionFecha2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cLocalidad` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nRecibo` int(11) DEFAULT '0',
  `Id_Cliente` int(11) DEFAULT '0',
  `cCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion1` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCp` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvincia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPais` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cConcepto` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rImporte` decimal(9,2) DEFAULT '0.00',
  `cImporte` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcionEntidad` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcionOficina` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cEntidad` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cOficina` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDC` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCuenta` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lCobrado` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `reservas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nReserva` int(11) DEFAULT '0',
  `dFecha` date DEFAULT NULL,
  `id_cliente` int(11) DEFAULT '0',
  `cCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDireccion2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cCP` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPoblacion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cProvincia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cPais` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTelefono1` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cTelefono2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFechaLimite` date DEFAULT NULL,
  `rImporte` decimal(9,2) DEFAULT '0.00',
  `rPendiente` decimal(9,2) DEFAULT '0.00',
  `rEntregado` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `secciones` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cSeccion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `sectores` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cSector` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `subfamilias` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cSubfamilia` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Id_Familia` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `tallas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Talla` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Id_ConceptoTalla` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `tareas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cTarea` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cAvisarA` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nDiasFecha` int(11) DEFAULT '0',
  `lCobros` int(11) DEFAULT '0',
  `lPagos` int(11) DEFAULT '0',
  `lObligacionesTributarias` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `tiposgasto` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cDescripcionTipoGasto` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cComentario` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `tiposiva` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cTipo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cDescripcionTipoIVA` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nIVA` decimal(9,2) DEFAULT '0.00',
  `nRegargoEquivalencia` decimal(9,2) DEFAULT '0.00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `vales` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nNumero` int(11) DEFAULT '0',
  `cCodigo` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dFecha` date DEFAULT NULL,
  `dVto` date DEFAULT NULL,
  `cDependient` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rImporte` decimal(9,2) DEFAULT '0.00',
  `IdTicket` int(11) DEFAULT '0',
  `Id_Cliente` int(11) DEFAULT '0',
  `cCliente` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lPagado` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;
